### ISSUE TITLE
Input from another AR sdk to Holistic Scene

### ISSUE THREAD

**Issue by KiranJodhani** [homuler/MediaPipeUnityPlugin#1045]
### Feature Description

@homuler

**Comment by homuler** [comment]
Could you please describe the problem more simply? For example, while you have mentioned something that is working, it's unclear how they relate to the overall issue. Consequently, I don't understand what you really want to know.

Now I will answer the questions based on what I have understood.

### TL; DR
You should not use `ImageSource` classes.
You should build an `ImageFramePacket` by yourself and send it to the `CalculatorGraph` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719 )

### Details
First, please note that source files under `Assets` are for the sample app.
You may use them but they are not intended to be used out of this project.
So you don't need to use `ImageSource` classes (e.g. `StaticImageSource`) to run the `CalculatorGraph` in your project.

To run the `CalculatorGraph`, you need to generate an input data (= `ImageFramePacket`) (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#send-imageframe ).
Once you've done that, there's no need to use `ImageSource` classes since the input data is already available.
Please read https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719 to see how to do that.

> Here I am little confused about type of Image source. What should be selected here as input? WebCamara or Image?

In the sample app, `ImageSource` class is a source of input images. For example, `StaticImageSource` can be used as the `Texture` generator of a static image and `WebCamSource` is a wrapper class of `WebCamTexture`.
However, there's no `ImageSource` class which returns the `ARCamera` image, which means there's no proper `ImageSource` that can be used in your case.

**Comment by KiranJodhani** [comment]
So what I am looking for is to take input from ARCamera instead of WebCam. 
So far what i have done is I generated Texture2D from Frame from ARCamera  as follows

`private void OnARCameraFrameReceived(ARCameraFrameEventArgs eventArgs)
  {
    arTextureToUpdate = GetCurrentColorTexture();
    OutputImage.texture = arTextureToUpdate;
  }

  unsafe Texture2D GetCurrentColorTexture()
  {
    if (!arCameraManager.TryAcquireLatestCpuImage(out XRCpuImage image))
      return null;

    XRCpuImage.ConversionParams conversionParams = new XRCpuImage.ConversionParams
    {
      inputRect = new RectInt(0, 0, image.width, image.height),
      outputDimensions = new Vector2Int(image.width, image.height),
      outputFormat = TextureFormat.RGBA32,
      transformation = XRCpuImage.Transformation.MirrorX
    };

    int size = image.GetConvertedDataSize(conversionParams);
    NativeArray<byte> buffer = new NativeArray<byte>(size, Allocator.Temp);

    image.Convert(conversionParams, new IntPtr(buffer.GetUnsafePtr()), buffer.Length);
    image.Dispose();

    if (arTexture == null)
    {
      arTexture = new Texture2D(conversionParams.outputDimensions.x, conversionParams.outputDimensions.y, conversionParams.outputFormat, false);
    }

    arTexture.LoadRawTextureData(buffer);
    arTexture.Apply();
    buffer.Dispose();
    return arTexture;
  }`

Now if I pass this texture 2d to HolisticTrackingGraph will this work?
Like what you said here https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-962349426
The only difference here is  ReadFromImageSource(imageSource, textureFrame);  is now in ImageSourceSolution<T>
Where T is HolisticTrackingGraph in my case
Hope this makes you clear
Please help Thanks

**Comment by homuler** [comment]
> Now if I pass this texture 2d to HolisticTrackingGraph will this work?

The answer is the followings:
> To run the CalculatorGraph, you need to generate an input data (= ImageFramePacket) (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#send-imageframe ).
Once you've done that, there's no need to use ImageSource classes since the input data is already available.
Please read https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719 to see how to do that.

> Like what you said here https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-962349426

I said that "please read https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1096698719", not https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-962349426.

Please read the implementation of the `OnCameraFrameReceived` method.

**Comment by KiranJodhani** [comment]
Thanks for the replay again

I think there is some mismatch in callback method

ARCameraManagerTest.cs(45,64): error CS0407: 'IntPtr ARCameraManagerTest.OutputCallback(IntPtr, int, IntPtr)' has the wrong return type

It gives me this error. I think it mismatch the correct paramenter

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/343#issuecomment-1773003981.

**Comment by KiranJodhani** [comment]
Thanks for the reply. It fixed the compile time error and I could see both ARCore face and I could see values in in `Debug.Log(detection);`
This works with face_detection_gpu.txt. However I am mainly looking for holistic solution. I tried to change text file from face_detection_gpu.txt to holistic_gpu.txt but it's not working. It gives error when i create apk. Below is error log.

MediaPipeException: NOT_FOUND: ; Unable to attach observer to output stream "face_detections" because it doesn't exist.
Mediapipe.Status.AssertOk () (at <00000000000000000000000000000000>:0)
ARCameraManagerTest+<Start>d__7.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)

MediaPipeException: FAILED_PRECONDITION: ; CalculatorGraph::AddPacketToInputStream() is called before StartRun()
Mediapipe.Status.AssertOk () (at <00000000000000000000000000000000>:0)
ARCameraManagerTest.OnCameraFrameReceived (UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs eventArgs) (at <00000000000000000000000000000000>:0)
UnityEngine.XR.ARFoundation.ARCameraManager.InvokeFrameReceivedEvent (UnityEngine.XR.ARSubsystems.XRCameraFrame frame) (at <00000000000000000000000000000000>:0)
UnityEngine.XR.ARFoundation.ARCameraManager.Update () (at <00000000000000000000000000000000>:0)

**Comment by homuler** [comment]
> MediaPipeException: NOT_FOUND: ; Unable to attach observer to output stream "face_detections" because it doesn't exist.

Isn't this error message explaining the cause sufficiently?
See also `HolisticTrackingGraph`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Assets/MediaPipeUnity/Samples/Scenes/Holistic/HolisticTrackingGraph.cs#L220-L227

If you've not finished [the tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial), I strongly recommend you finish it first.

**Comment by KiranJodhani** [comment]
I tried tutorial but I could not make it work. I followed same steps. I am getting this error
ArgumentException: WebCamTexture.GetPixels32: the size of data to be written to would result in writing outside the target buffer bounds. (Texture '')
Mediapipe.Unity.Tutorial.FaceMesh+<Start>d__12.MoveNext () (at Assets/MediaPipeUnity/Tutorial/Official Solution/FaceMesh.cs:67)
Since holistic scene is working fine without ARCamara, to be honest I never needed to make any change. I used that scene as base and applied my calculation. Now the challenge is I am planning to use ARFoundation with this scene and struggeling to make it work. 
I will definitely look into the HolisticTrackingGraph but first I am yet to understand why sample is not working
