### ISSUE TITLE
Getting compile errors in the packages. 

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#105]
![image](https://user-images.githubusercontent.com/43686606/112339118-64b64b80-8ce5-11eb-8cc4-752a93d27b10.png)

Hello @homuler! I tried to run your project using the documentation you have provided. 
But getting some compile errors in the runtime packages folder, most of them are saying that some namespace or type is missing. Could you please help me know where I got the installation wrong?

I'm running this on a Windows desktop and Unity version is 2019.4.22f1

**Comment by homuler** [comment]
Will you share the command you executed to build (e.g. `python build.py --desktop gpu -v`) and the output log?
I guess you've failed to build native libraries.

**Comment by midopooler** [comment]
![image](https://user-images.githubusercontent.com/43686606/112434292-688bb180-8d69-11eb-93c6-7977bc25cba3.png)

I didn't rebuild it. I took a screenshot when I did it first.

**Comment by homuler** [comment]
Please set `PYTHON_BIN_PATH` (see https://github.com/homuler/MediapipeUnityPlugin#installation No. 4).
In addition, you cannot build native libraries with GPU enabled on Windows, so please run `python build.py build --desktop cpu -v` instead.

**Comment by midopooler** [comment]
I followed your above steps and getting these logs 
![image](https://user-images.githubusercontent.com/43686606/112991390-b008a800-9184-11eb-9440-eadeb908f839.png)

The reason for a late reply from my side is that I'm really struggling with MediaPipe. :(

**Comment by midopooler** [comment]
Okay, I somehow managed to set the bin path correctly. Will raise another issue on why it wasn't working well. 

But, the problem is that I'm still getting those same compile errors now again (read my first comment again) and this is the console 
![image](https://user-images.githubusercontent.com/43686606/113292539-474f3600-9312-11eb-8c8a-6fc3090fe550.png)

**Comment by FedericoRubinstein** [comment]
I was able to replicate the first issue, the problem is that the build.py script doesn't allow the PYTHON_BIN_PATH to have any spaces, and putting " around the path doesn't fix it either, since the path ends up being `""C:/path/to/python.exe""` on the bazel command, which is wrong. 

A solution for this is simply installing python on a path without spaces, however, I think that the build.py script can be easily changed to accept spaces (see the image for a quick fix I made to the script that seems to work fine). 

![image](https://user-images.githubusercontent.com/33610362/113319516-c8f29400-9311-11eb-83ff-d91831d4749c.png)

**Comment by homuler** [comment]
@midopooler Please install NuGet.
@FedericoRubinstein Thank you, now I see.

**Comment by midopooler** [comment]
I'm finally able to run the project successfully without any compile errors. Thanks a lot! @homuler @FedericoRubinstein
