### ISSUE TITLE
 Slow joint information processing

### ISSUE THREAD

**Issue by jameslee0227** [homuler/MediaPipeUnityPlugin#1052]
### Description

coroutine is compatible and stable in Unity, but is slow.
I would like to suggest a way to improve this.
When using the method of storing in the image queue and processing in callback and thread, the response time was 1.5 to more than 2 times faster.
We look forward to improving speed.

**Comment by homuler** [comment]
Which API is the issue related to?
I didn't intend to provide an API that requires Coroutine, so please let me know if there is one.

**Comment by jameslee0227** [comment]
Dear Junrou Nishida

I hope this message finds you well. I am writing to express our sincere
gratitude for making the MediaPipeUnityPlugin publicly available. It has
been an invaluable asset for our team.

We have recently encountered an aspect of the plugin that raised some
questions. Our developer, [Developer's A], has observed that the current
implementation of MediaPipeUnityPlugin uses coroutines for processing joint
information, which appears to slow down the processing speed. However, upon
experimenting with threads, [Developer's A] found a significant improvement
in performance, including faster response times of the joints.

Based on this experience, we are curious about your perspective on the
current performance of the MediaPipeUnityPlugin and whether there is room
for improvement in this regard. We would greatly appreciate your thoughts
and any suggestions you might have.

Looking forward to your response and thank you once again for developing
such a useful tool.

Best regards,

James


2023년 11월 28일 (화) 오후 8:24, Junrou Nishida ***@***.***>님이 작성:

**Comment by homuler** [comment]
> the current
implementation of MediaPipeUnityPlugin uses coroutines for processing joint
information

Will you tell me the exact line of code (the GitHub URL, e.g. [VisionTaskApiRunner.cs#L28](https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Assets/MediaPipeUnity/Samples/Common/Scripts/VisionTaskApiRunner.cs#L28)), please?

**Comment by homuler** [comment]
Since there is no response, I will close this issue, but I would like to provide some additional clarification.

Firstly, as a design principle for plugins, I intend to avoid APIs that require the use of Coroutine. Therefore, if there is something that cannot be implemented without using Coroutine when assuming the APIs provided by the plugin, please let me know, and I will fix it.

On the other hand, in the sample application (code located under `Assets/`), Coroutine is used. It's important to note that this is merely a sample, and it does not imply that Coroutine must be used in all cases.

I don't want to add dependencies if possible, so in the sample, I'm using Coroutine. However, I also anticipate that the plugin may be used in conjunction with libraries such as UniTask.
