### ISSUE TITLE
Where to declare Face Detection model in Iris Tracker Sample?

### ISSUE THREAD

**Issue by mattycorbett** [homuler/MediaPipeUnityPlugin#1054]
### Plugin Version or Commit ID

0.12.0

### Unity Version

2022.2.19

### Your Host OS

Windows 11

### Target Platform

Android

### Description

I am trying to understand the Iris Tracking sample that you built. I noticed that the sample loads the face_detection_short_range.bytes file for face detection before the detections are passed to the landmarker, etc. Is there a way to change this in the sample? I don't see it declared anywhere to load this model, I only see where the IrisTrackingGraph loads the resource.

**Comment by homuler** [comment]
> I don't see it declared anywhere to load this model, I only see where the IrisTrackingGraph loads the resource.

It is hard-coded on the MediaPipe side.
https://github.com/google/mediapipe/blob/91589b10d3c684af00cf8e3d14e4683797ab55bd/mediapipe/modules/face_detection/face_detection_short_range.pbtxt#L37

> Is there a way to change this in the sample?

Yes, but I don't think there is a straightforward way.

- [Apply a patch](https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/WORKSPACE#L38-L44)
- Use the `FaceDetection` calculator directly in your graph config
- Implement your own `ResourceManager` and translate the hard-coded path
  - see [`StreamingAssetsResourceManager.PathToResourceAsFile`](https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/StreamingAssetsResourceManager.cs#L65-L69) (it translates `mediapipe/modules/face_detection/face_detection_short_range.tflite` to `face_detection_short_range.bytes`)


On the other hand, using the [Task API](https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarker.cs) (instead of `IrisTrackingGraph` ) allows for specifying the path.
https://github.com/homuler/MediaPipeUnityPlugin/blob/2d2863ea740a6a5ad01854ea88ab5f48be2a36b6/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face%20Landmark%20Detection/FaceLandmarkDetectionConfig.cs#L28-L33

**Comment by mattycorbett** [comment]
Thank you!  I was able to get this working by updating the config files for both the CPU and GPU. For reference, here there are.
[iris_tracking_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/13573281/iris_tracking_cpu.txt)
[iris_tracking_gpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/13573282/iris_tracking_gpu.txt)
