### ISSUE TITLE
Appearance and disappearance of key points on android devices

### ISSUE THREAD

**Issue by MARLOPD** [homuler/MediaPipeUnityPlugin#1169]
### Description

In the unity editor the app shows continuously the keypoints, however, on the cell phone they appear and disappear even when the person remains still, I thought it was something in the phone so I tried it on the following devices:

MotorolaG200
Redmi 11
Redmi Note 13
Samsung A34
Redmi Note 11
Samsung Note 10
Redmi 12
Xiaomi mi Lite 11
Oppo A 38

In none of the previous devices the problem was solved.

The app works really good in the Unity editor, but at the moment of building and test in the devices I have this problem; however there is no error in Logcat

**Comment by homuler** [comment]
Please use the [support form](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/support.yml) (I would like you to specify the versions of both the plugin and Unity at least).

In general, please provide logs even if there are no errors (enable `Development Build`).
For now, it's not even clear which scenes are being run with what settings. Also, if possible, I would like you to attach a video. It's not accurately understood what is happening from just text.

Based on the information available now, if you are running in Async mode, I believe the issue is due to a low value set for `timeoutMillisec` (you can set it from the [UI](https://github.com/homuler/MediaPipeUnityPlugin/issues/821#issuecomment-1397080703). See also https://github.com/homuler/MediaPipeUnityPlugin/issues/661#issuecomment-1189705966).

`timeoutMillisec` is used to control the `emptyPacketThresholdMicrosecond` argument.
https://github.com/homuler/MediaPipeUnityPlugin/blob/638e3cf7faeb544a62e5292f7354d2f8af831ba7/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs#L200-L214

> even if the output must be present

In your case, this could be paraphrased "even when the person remains still".

**Comment by homuler** [comment]
Note that the sample application is designed to make it as easy as possible to verify the behavior of MediaPipe (assuming that this issue lies not with the plugin itself but with the sample app).
Therefore, when incorporating the plugin into a real application, I believe there are various mitigation measures available.

**Comment by MARLOPD** [comment]
Thank you so much! The problem rely on timeoutMillisec
