### ISSUE TITLE
[Mediapipe supports Windows] No more experimental build

### ISSUE THREAD

**Issue by GeorgeS2019** [homuler/MediaPipeUnityPlugin#1189]
### Feature Description

Currently windows build support has been always experimental.

By combining our request, we could **ask for no longer experimental build.**

The GDMP repos has established **VS2019** CI build of **v0.10.13**

https://github.com/j20001970/GDMP/actions/runs/9025015499

https://github.com/cosyneco/MediaPipe.NET/issues/65#issuecomment-2103692239

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/49812372/abf0275c-819b-4c1f-be35-25d895e58395)

**Comment by homuler** [comment]
The reason why Windows support is experimental is not because it cannot be built, but because MediaPipe itself does not officially support it.
https://developers.google.com/mediapipe/framework/getting_started/faq#can_i_run_mediapipe_on_ms_windows

**Comment by homuler** [comment]
So? It seems to me that the situation hasn't changed yet.

**Comment by GeorgeS2019** [comment]
@homuler 
I do not have sufficient technical know how to see what could be the challenges for your repos to develop CI build against e.g. v0.10.13

Do U have plan to do that?

Now that Godot 4 has CI, we hope to feedback to the Google team, of there is, any break

Ideally, whatever the latest features, the feedback needed by Google, will be much more wide user based, if both Godot and Unity and hopefully tensorflow lite provide rapid iteration

**Comment by homuler** [comment]
It appears that there is a discrepancy in the understanding of _experimental_ between us.

First of all, the reason why Windows support is labeled as experimental is that MediaPipe does not officially support it, and there is no other reason.

Also, in my opinion, [the issue](https://github.com/google/mediapipe/issues/5366) you are sharing has no relation to the fact that MediaPipe's Windows support is experimental.
In other words, I don't think that resolving that issue would have any impact on its experimental status, [as was already mentioned](https://github.com/homuler/MediaPipeUnityPlugin/issues/1189#issuecomment-2105585863).

> A deeper discussion about official Windows platform support should probably occur on a separate issue, as there may be many other contributing factors (such as 3rd party dependencies, or spaces in filenames disrupting scripts) resulting in the mediapipe team deciding Windows support warrants being kept as experimental.

Separately, regarding the fact that the version of MediaPipe this plugin depends on is not the latest (v0.10.13), this also has no relation to the issue you are sharing; it's simply because I've been spending time on other projects, causing delays in the update process.

Are you hoping that the version of MediaPipe will be updated to v0.10.13?
If so, there is already [another issue ](https://github.com/homuler/MediaPipeUnityPlugin/issues/1151) for that.

**Comment by vo6i** [comment]
> It appears that there is a discrepancy in the understanding of _experimental_ between us.
> 
> First of all, the reason why Windows support is labeled as experimental is that MediaPipe does not officially support it, and there is no other reason.
> 
> Also, in my opinion, [the issue](https://github.com/google/mediapipe/issues/5366) you are sharing has no relation to the fact that MediaPipe's Windows support is experimental. In other words, I don't think that resolving that issue would have any impact on its experimental status, [as was already mentioned](https://github.com/homuler/MediaPipeUnityPlugin/issues/1189#issuecomment-2105585863).
> 
> > A deeper discussion about official Windows platform support should probably occur on a separate issue, as there may be many other contributing factors (such as 3rd party dependencies, or spaces in filenames disrupting scripts) resulting in the mediapipe team deciding Windows support warrants being kept as experimental.
> 
> Separately, regarding the fact that the version of MediaPipe this plugin depends on is not the latest (v0.10.13), this also has no relation to the issue you are sharing; it's simply because I've been spending time on other projects, causing delays in the update process.
> 
> Are you hoping that the version of MediaPipe will be updated to v0.10.13? If so, there is already [another issue ](https://github.com/homuler/MediaPipeUnityPlugin/issues/1151) for that.

Please you can ask me? [Question](https://github.com/homuler/MediaPipeUnityPlugin/issues/1190)
