### ISSUE TITLE
Could not find type "type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions"

### ISSUE THREAD

**Issue by fathole** [homuler/MediaPipeUnityPlugin#1193]
### Plugin Version or Commit ID

v0.14.3

### Unity Version

2022.3.16f1

### Your Host OS

Window 10

### Target Platform

UnityEditor

### Description

I am trying to make the face effect in unity. It log the error when i parse the config asset [ https://github.com/google-ai-edge/mediapipe/blob/master/mediapipe/graphs/face_effect/face_effect_gpu.pbtxt](url). 

![FaceEffect](https://github.com/homuler/MediaPipeUnityPlugin/assets/76873753/f68f99a3-0cc9-4fa0-80a4-5afcb4e2daa2)

**Comment by homuler** [comment]
To use FaceEffect, you need to add the necessary bazel target to [the `deps`](https://github.com/homuler/MediaPipeUnityPlugin/blob/bd417bfd463d2da9cae0d9f9f7d29dd9ef4fabe6/mediapipe_api/BUILD#L279-L299), and rebuild it yourself.
However, since it does not seem to be officially supported, if you actually want to do it, I think it would be better to use [the transformation matrix](https://github.com/homuler/MediaPipeUnityPlugin/blob/bd417bfd463d2da9cae0d9f9f7d29dd9ef4fabe6/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerOptions.cs#L69-L74) obtained from the `Face Landmarker` and implement it yourself.
