### ISSUE TITLE
[question] Can't build desktop library for windows on Linux?

### ISSUE THREAD

**Issue by Leuconoe** [homuler/MediaPipeUnityPlugin#121]
First of all, thank you for releasing a great project.

I know that I can't build a library for Android in the windows workspace. So I built the library using wsl2.
However, libraries built on Linux are only available for Linux and OSX platforms.
So, I built using the desktop flag in windows, and when the built packages were merged, there was no error in the windows editor, and the Android build was fine.

If you want to develop for Android in the windows workspace, is it correct to build the library on both platforms, linux and windows?

Thank you.

**Comment by homuler** [comment]
> is it correct to build the library on both platforms, linux and windows?

For now, yes.

To run this plugin on UnityEditor on Windows, `libmediapipe_c.dll` is required, and it can be only built on **Windows** (because Windows 10 SDK is needed).
On the other hand, to run it on Android, `mediapipe_android.aar` is required.
Ideally, `mediapipe_android.aar` can be built on Windows, but currently we can't do that (maybe this is a Tensorflow's bug), so you need to build it on other platforms.

By the way, I updated this repo recently and now you can build `mediapipe_android.aar` with Docker container on Windows.
https://github.com/homuler/MediaPipeUnityPlugin#android

**Comment by Leuconoe** [comment]
Thank you for answer.
I'll try building with docker later.
