### ISSUE TITLE
Pass pointer address of texture instead of colors32

### ISSUE THREAD

**Issue by elblogbruno** [homuler/MediaPipeUnityPlugin#13]
I believe the repo is awesome, but having some FPS or milliseconds improvement is a good thing to develop 
So , one thing in my mind for some time is that in unity you can get the texture image pointer address and I ask if it could be passed directly,so mediapipe access it instead of Colors32 that is a very expensive operation. I simply had the idea don't know how to implement it tough.

Thanks and great job.
Bruno

**Comment by elblogbruno** [comment]
@homuler here there's more info about how to get the pointer adress https://docs.unity3d.com/ScriptReference/Texture.GetNativeTexturePtr.html

**Comment by homuler** [comment]
@elblogbruno  Thank you for reporting the issue.

Currently, [DemoGraph#PushInput](https://github.com/homuler/MediaPipeUnityPlugin/blob/40dfc7054d6307b0149f697ed857a7942cd07122/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs#L39) copies GPU buffer to ImageFrame (CPU memory) and copies `ImageFrame` data to GPU buffer again. The good thing is that it needs less native APIs (so I can implement fast), but those operations are unnecessary and expensive as you pointed out.

I'll change the code to pass the GL texture name to MediaPipe directly, but it looks difficult to do with the current architecture (because Unity have to know when to release which GL texture), so it may take time.

**Comment by elblogbruno** [comment]
Glad my comment was useful for you and that it can be implemented in the near future!
I believe in the URL I had passed previously, there are algorithm examples.

Cordially
Bruno

**Comment by homuler** [comment]
Finally...we can now pass the texture's native pointer (or texture name) to MediaPipe (OpenGL ES only).
https://github.com/homuler/MediaPipeUnityPlugin/blob/18e00a85ac271b123178e593184184e8715ed22e/Assets/MediaPipe/Examples/Scripts/DemoGraph.cs#L54-L63

We can also ask MediaPipe to render the output to a Unity Texture directly (cf. [OfficialDemoGPU](https://github.com/homuler/MediaPipeUnityPlugin/blob/18e00a85ac271b123178e593184184e8715ed22e/Assets/MediaPipe/Examples/Scripts/OfficialDemo/OfficialDemoGPU.cs#L47-L61))

But in fact `OfficialDemoGPU` does not perform as well as the official APK, I'll continue to investigate to improve the performance.

Memo (performance tips)
- Build a GpuBuffer object from the input texture's name and pass it to MediaPipe (OpenGL ES only)
- Use `CalculatorGraph#ObserveOutputStream` and get output packets asynchronously (cf. [OfficialDemoCPU](https://github.com/homuler/MediaPipeUnityPlugin/blob/18e00a85ac271b123178e593184184e8715ed22e/Assets/MediaPipe/Examples/Scripts/OfficialDemo/OfficialDemoCPU.cs#L16))

**Comment by elblogbruno** [comment]
I can't wait to try it! Glad the idea was able to be implemented, have you noticed improvement?
Thanks for all!
Great job

**Comment by elblogbruno** [comment]
I am getting better performance (50-60fps 10ms) on OfficialDemoGPU than hand graph

https://user-images.githubusercontent.com/10481058/103406106-d3a65d00-4b59-11eb-8700-49935c42f868.mp4
