### ISSUE TITLE
WSL2 <> Unity

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#162]
**System information**
- OS Platform and Distribution:- Windows/WSL2
- Target:- android arm64

The instructions are given for the WSL2 on the Readme.MD of this repo is a bit unclear to me since I'm a complete beginner in WSL2.
 I have followed all the steps and got the android build in Ubuntu. 
![image](https://user-images.githubusercontent.com/43686606/117969831-8aef8380-b345-11eb-9007-72f004ae1257.png)

Now I'm clueless about how to run this project in Unity. Do I have to install Unity as well in WSL? (Idk if that's even possible or not) Or is there any way from which I can access those built libraries from WSL to windows native.

**Comment by horatiu665** [comment]
Hey! Totally noob here. I managed to build for windows using docker, and got the project to work in Unity by running Unity on my regular windows machine, and copying the DLLs resulting from the build from inside docker (or rather, copying the entire package into my project/Packages folder). I suspect the same process might work for Android: I suspect there should be a file called "mediapipe_android.aar" after you build, copy that one into the "Packages\com.github.homuler.mediapipe\Runtime\Plugins\Android" and you should be golden.

Side-note: it would be super nice if any of the fine folks managing this repo could post a release of the built libraries for the different platforms, because it's such a pain to figure out how to build ourselves. Maybe not for every version but at least something :)

Hope this helps! Cheers!

**Comment by homuler** [comment]
If you've set up WSL2, I think to use [Docker for Windows](https://docs.docker.com/docker-for-windows/install/) is much easier.
cf. https://github.com/homuler/MediaPipeUnityPlugin#android

> and copying the DLLs resulting from the build from inside docker 

@horatiu665  If you mount `Packages` folder to the container as described [here](https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor), you don't need to copy DLLs manually.
