### ISSUE TITLE
Changing shoe model at runtime

### ISSUE THREAD

**Issue by emreboyraz0** [homuler/MediaPipeUnityPlugin#168]
I am working on objectron3d feature and testing sneakers.

I want to change sneakers when i tap a button at runtime, but I could not succeed in this.
Can you help how can i change one sneaker to another at runtime?
regards

**Comment by homuler** [comment]
> I want to change sneakers 

Is that you'd like to switch [Category](https://github.com/homuler/MediaPipeUnityPlugin/blob/8c171d0eb2d16140ea94511d3dd6c94cf3792804/Assets/Mediapipe/Samples/Graphs/ObjectDetection3d/Scripts/ObjectDetection3dGraph.cs#L11) from `Sneaker` to `Chair`?
Or you'd like to switch the sneaker model to be rendered on the screen?

In the latter case, since the sample app don't have such a feature, will you share the minimum code, please?
From the current description, I can't judge if this issue is related to MediaPipe or not.

**Comment by emreboyraz0** [comment]
"Or you'd like to switch the sneaker model to be rendered on the screen?"

For example I have 2 sneaker model (shoe1.obj.bytes and shoe2.obj.bytes). I want to change sneaker models 1 to 2.

**Comment by homuler** [comment]
If you're using `GlAnimationOverlayCalculator`, then model files are loaded only once, so you need to restart `CalculatorGraph`.
I've not tested, but I guess you can do that by calling `CalculatorGraph#Close` or `CalculatorGraph#WaitUntilDone`, and `CalculatorGraph#StartRun` again.

However, on Unity, I suppose it's usually better to render texture by yourself than to render it with MediaPipe.

**Comment by emreboyraz0** [comment]
"However, on Unity, I suppose it's usually better to render texture by yourself than to render it with MediaPipe."

Could not understand that I am sorry. How can i render texture by myself than to render it?

**Comment by emreboyraz0** [comment]
> I've not tested, but I guess you can do that by calling CalculatorGraph#Close or CalculatorGraph#WaitUntilDone, and CalculatorGraph#StartRun again.
Seems to work
