### ISSUE TITLE
Built APK

### ISSUE THREAD

**Issue by Zumbalamambo** [homuler/MediaPipeUnityPlugin#19]
For some reason, it just wont let me build an apk out of it. Could you please share the built apk?

**Comment by midopooler** [comment]
+1, Please add a built APK in the repo itself so that everyone can have an idea of how it works on their devices. 
@homuler

**Comment by midopooler** [comment]
@homuler 
Going through your above reply. 
It seems like you misinterpreted my question. 

**I am asking for the .apk file of desktopdemo.unity scene so that I can try it on my phone.** 

I have your repository running on my Windows desktop and it's building for windows (.exe). Now before moving to WSL 2 so that I could build it on android, I need to see how the app runs on my mobile phone and that's what I'm asking for. 
Thanks!!

**Comment by homuler** [comment]
I may publish the sample app on Play Store if I feel like it, but at least I won't do that soon.
