### ISSUE TITLE
Adding Selfie Segmentation in this repository

### ISSUE THREAD

**Issue by midopooler** [homuler/MediaPipeUnityPlugin#195]
Hey @homuler , as you might be aware of this brand new solution added into Mediapipe recently: Selfie Segmentation

**https://google.github.io/mediapipe/solutions/selfie_segmentation.html**

Do you have any plans to add this solution to this repository? If not, Please guide me on how to add it and I would love to contribute to your repo! :D

**Comment by homuler** [comment]
Yeah, I'm trying upgrading mediapipe to v0.8.5 and adding selfie segmentation sample.
However, I found some issues around `FlowLimiterCalculator` and `PacketPresenceCalculator`, and I'm fixing them now first.

**Comment by midopooler** [comment]
`Yeah, I'm trying upgrading mediapipe to v0.8.5 and adding selfie segmentation sample.`
Thats very cool to know. 

`However, I found some issues around FlowLimiterCalculator and PacketPresenceCalculator, and I'm fixing them now first.`
Let me know if I could help here!

**Comment by midopooler** [comment]
Hi, Is it included in the branch `mediapipe-0.8.6` ?
https://github.com/homuler/MediaPipeUnityPlugin/tree/build/mediapipe-0.8.6

**Comment by NathanielEssenberg** [comment]
I am interested in Selfie Segmentation as well, so I hope it will be possible :)

**Comment by olokobayusuf** [comment]
@NathanielEssenberg pending when the model is added to this library, you can [play with the model](https://hub.natsuite.io/predictor/@natsuite/hand-pose) with [NatML](https://github.com/natsuite/NatML).

**Comment by mimisuar** [comment]
If I wanted to add the selfie segmentation myself, would I have to recompile the entire plugin?

**Comment by homuler** [comment]
@mimisuar Please add dependent targets to [`calculators`' `deps`](https://github.com/homuler/MediaPipeUnityPlugin/blob/efc7664e3ed5d997ee618c364bd2256896a43aae/mediapipe_api/BUILD#L98) and built libraries again.

**Comment by fabiomatsui-acn** [comment]
Has anyone been able to complete Selfie Segmentation implemented? If not, any other tips on what needs to be done to finish the implementation?

**Comment by olokobayusuf** [comment]
@fabiomatsui-acn NatML for Unity has the segmentation model that works on Android, iOS, macOS, and Windows. See [`@natsuite/meet-segmentation`](https://hub.natml.ai/@natsuite/meet-segmentation).

**Comment by fabiomatsui-acn** [comment]
I was hoping to stay with MediaPipeUnityPlugin and I feel I'm close. I just need to solve an image frame format issue. Currently ImageFrame.cs does not support VEC32F1. So I tried to use RecolorCalculator to create RGB or RGBA but it doesn't support RGBA inputs which the Unity side is providing. Anyone has suggestions on how to get around this?

**Comment by homuler** [comment]
@fabiomatsui-acn Will you share the current code and `CalculatorGraphConfig` (+ error message) that are not working well?
I have not checked Selfie Segmentation yet, but I thought it could work in a similar way to Hair Segmentation.

**Comment by fabiomatsui-acn** [comment]
I had the same though of starting with Hair Segmentation. I used this graph config which is basically MediaPipe's .pbtxt.

[selfie_segmentation_cpu.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/8211659/selfie_segmentation_cpu.txt)

I get the following error in Unity which I assume is because RecolorCalculator doesn't like RGBA.

MediaPipeException: INTERNAL: Graph has errors: 
Calculator::Process() for node "RecolorCalculator" failed: ; input_mat.channels() == 3al/com_google_mediapipe/mediapipe/calculators/image/recolor_calculator.cc:241) 
Mediapipe.Status.AssertOk () (at Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs:48)
Mediapipe.Unity.GraphRunner.AddPacketToInputStream[T] (System.String streamName, Mediapipe.Packet`1[T] packet) (at Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs:183)
Mediapipe.Unity.GraphRunner.AddTextureFrameToInputStream (System.String streamName, Mediapipe.Unity.TextureFrame textureFrame) (at Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs:200)
Mediapipe.Unity.SelfieSegmentation.SelfieSegmentationGraph.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/Mediapipe/Samples/Scenes/SelfieSegmentation/SelfieSegmentationGraph.cs:51)
Mediapipe.Unity.SelfieSegmentation.SelfieSegmentationSolution.AddTextureFrameToInputStream (Mediapipe.Unity.TextureFrame textureFrame) (at Assets/Mediapipe/Samples/Scenes/SelfieSegmentation/SelfieSegmentationSolution.cs:25)
Mediapipe.Unity.ImageSourceSolution`1+<Run>d__12[T].MoveNext () (at Assets/Mediapipe/Samples/Common/Scripts/ImageSourceSolution.cs:103)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3be1a7ff939c43f181c0a10b5a0189ac>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by homuler** [comment]
> I get the following error in Unity which I assume is because RecolorCalculator doesn't like RGBA.

It seems so.
https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/calculators/image/recolor_calculator.cc#L241

How about removing `RecolorCalculator` like the Hair Segmentation sample?
This is not necessary unless you want to do masking in C++.

**Comment by fabiomatsui-acn** [comment]
I tried removing `RecolorCalculator` but currently `ImageFrame.cs` does not support `VEC32F1` which is the output of `SelfieSegmentationCpu`

**Comment by homuler** [comment]
I see.
I understand that it needs to be supported as a plugin, I will check it later.

At least, I think you can read the result value using `ImageFrame#MutablePixelData`, but possibly you could also use `ImageFrame#CopyToFloatBuffer`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/c7a33ba8f1d1f57fa34932d7842da273317b3b93/Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Format/ImageFrameTest.cs#L196-L206

**Comment by fabiomatsui-acn** [comment]
This was a great tip. I did a quick and dirty test and I was able to copy the `ImageFrame` buffer into a `Texture2D` set with texture format `TextureFormat.RFloat` and I could visualize the mask.
