### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by MRLesile** [homuler/MediaPipeUnityPlugin#264]
![image](https://user-images.githubusercontent.com/24579953/131646660-ec80cf26-e0ff-4809-92c9-b549ad92298a.png)

**Comment by homuler** [comment]
Where have you installed OpenCV?
https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor-1

**Comment by MRLesile** [comment]
Unity Can Run 

> Where have you installed OpenCV?
> https://github.com/homuler/MediaPipeUnityPlugin#desktopunityeditor-1
Now,UnityEditor Can Run, But Build For Exe,Not Find DLL mediapipe_c


![image](https://user-images.githubusercontent.com/24579953/131656924-b0612f04-7fa6-47b8-ae47-68552efb023e.png)


this is mu Bundle And  sure Windows Platform

**Comment by homuler** [comment]
Please tell me your system information in the way like [this format](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-installation-issue.md) and also share the `Editor.log`.
See also https://github.com/homuler/MediaPipeUnityPlugin/issues/260#issuecomment-910148422 and https://github.com/homuler/MediaPipeUnityPlugin/issues/260#issuecomment-910151456 , since it may be the same issue.

**Comment by MRLesile** [comment]
DEBUG (build.py): Running `bazel build -c opt //mediapipe_api:mediapipe_proto_srcs`
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/org_tensorflow/third_party/repo.bzl:108:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_zl/6de371e6cb5a92efe862db2fb0286ee5/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: The repository's path is "/usr/local/opt/android-sdk" (absolute: "/usr/local/opt/android-sdk") but a symlink could not be created for it, because: /usr/local/opt/android-sdk (No such file or directory)
INFO: Elapsed time: 2.392s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (22 packages loaded, 22 targets configured)
    currently loading: @rules_foreign_cc//foreign_cc/private/shell_toolchain/toolchains ... (4 packages)
Traceback (most recent call last):
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 392, in <module>
    Argument().command().run()
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/Users/zl/data/MediaPipeUnityPlugin/build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', 'build', '-c', 'opt', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.





Build Android aar Error

**Comment by homuler** [comment]
Well, please write your **System Information!** (cf. https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/.github/ISSUE_TEMPLATE/build-installation-issue.md)

It's created as a Windows issue, but you're running it on macOS now, right?
And apparently you've changed the command but you've not written the new command, so I cannot get what you're trying to do.

What I can tell you now is that maybe you are trying to build for Android, but are failing because the path to the SDK (i.e. `ANDROID_HOME`) is wrong.
> The repository's path is "/usr/local/opt/android-sdk" (absolute: "/usr/local/opt/android-sdk") but a symlink could not be created for it, because: /usr/local/opt/android-sdk (No such file or directory)

So maybe you need to install Android SDK and NDK, and set the path to `ANDROID_HOME` and `ANDROID_NDK_HOME`.

**Comment by MRLesile** [comment]
> 好吧，请写下您的**系统信息！**（参见https://github.com/homuler/MediaPipeUnityPlugin/blob/d58ab72c8149fce183ce804aef2e218f74ff70dc/.github/ISSUE_TEMPLATE/build-installation-issue.md）
> 
> 它是作为 Windows 问题创建的，但您现在正在 macOS 上运行它，对吗？
> 显然你已经改变了命令，但你没有编写新命令，所以我无法理解你想要做什么。
> 
> 我现在可以告诉您的是，您可能正在尝试为 Android 构建，但由于 SDK（即`ANDROID_HOME`）的路径错误而失败。
> 
> > 存储库的路径是“/usr/local/opt/android-sdk”（绝对：“/usr/local/opt/android-sdk”）但无法为其创建符号链接，因为：/usr/local/opt /android-sdk（没有那个文件或目录）
> 
> 所以也许你需要安装Android SDK和NDK，并将路径设置为`ANDROID_HOME`和`ANDROID_NDK_HOME`。

I have the SDK and NDK installed, but where should I get my repository address from

Modify the

**Comment by Chinedu25** [comment]
I get this error building on windows whats the problem

INFO: Analyzed target //mediapipe_api:mediapipe_assets (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/bbc/downloads/mediapipeunityplugin-master/mediapipeunityplugin-master/mediapipe_api/graphs/instant_motion_tracking/BUILD:5:8: Executing genrule //mediapipe_api/graphs/instant_motion_tracking:asset3d failed: (Exit 127): bash.exe failed: error executing command
  cd /d C:/_bzl/lbr7m5x6/execroot/mediapipe_api
  SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Users\bbc\bin;D:\Programs\Git\mingw64\bin;D:\Programs\Git\usr\local\bin;D:\Programs\Git\usr\bin;D:\Programs\Git\usr\bin;D:\Programs\Git\mingw64\bin;D:\Programs\Git\usr\bin;C:\Users\bbc\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;D:\Programs\Git\cmd;C:\src\flutter\bin;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;D:\OpenCv\CurrentBin\bin;D:\OpenCv\CurrentBin\bin;D:\AppData\AndroidSdk;D:\AppData\AndroidSdk\platform-tools;C:\Program Files\Java\jdk-15.0.2\lib;C:\Program Files\Java\jdk-15.0.2\bin;C:\msys64\usr\bin;C:\Bazel\bazel.exe;C:\Bazel;C:\Bazel\nuget.exe;C:\Python39\Scripts;C:\Python39;C:\Users\bbc\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\bbc\AppData\Local\Programs\Python\Python39;C:\Users\bbc\AppData\Local\Microsoft\WindowsApps;D:\Programs\Microsoft VS Code\bin;C:\Users\bbc\AppData\Local\GitHubDesktop\bin;C:\src\flutter\bin;C:\Users\bbc\AppData\Roaming\npm;D:\OpenCv\CurrentBin\bin;D:\OpenCv\CurrentBin\bin;D:\AppData\AndroidSdk;D:\AppData\AndroidSdk\platform-tools;C:\Program Files\Java\jdk-15.0.2\bin;C:\Program Files\Java\jdk-15.0.2\lib;C:\Program Files\Java\jdk-15.0.2\bin;C:\msys64\usr\bin;C:\Bazel\bazel.exe;C:\Bazel;C:\Bazel\nuget.exe;D:\Programs\Git\usr\bin\vendor_perl;D:\Programs\Git\usr\bin\core_perl
    SET PYTHON_BIN_PATH=C://Python39//python.exe
    SET RUNFILES_MANIFEST_ONLY=1
  C:\msys64\usr\bin\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh; unzip -p external/com_google_mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/instantmotiontracking/assets/robot/robot.obj.uuu.zip > bazel-out/x64_windows-opt/bin/mediapipe_api/graphs/instant_motion_tracking/robot/robot.obj.uuu
Execution platform: @local_execution_config_platform//:platform
      0 [main] unzip (18684) D:\Programs\Git\usr\bin\unzip.exe: *** fatal error - cygheap base mismatch detected - 0x180352408/0x18034C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Target //mediapipe_api:mediapipe_assets failed to build
INFO: Elapsed time: 0.714s, Critical Path: 0.33s
INFO: 6 processes: 2 internal, 4 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "c:\Users\bbc\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 392, in <module>
    Argument().command().run()
  File "c:\Users\bbc\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 126, in run
    self._run_command(self._build_resources_commands())
  File "c:\Users\bbc\Downloads\MediaPipeUnityPlugin-master\MediaPipeUnityPlugin-master\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Python39//python.exe', '--verbose_failures', '//mediapipe_api:mediapipe_assets']' returned non-zero exit status 1.

**Comment by homuler** [comment]
> unzip (18684) D:\Programs\Git\usr\bin\unzip.exe: *** fatal error - cygheap base mismatch detected - 0x180352408/0x18034C408.
This problem is probably due to using incompatible versions of the cygwin DLL.

Well, it's totally different problem so I'd rather like you to create a new issue.
You're running `bash`, that is installed by `msys64`, but calling `unzip` that is installed by `Git for Windows`.
You need to configure your machine so that msys64's `unzip` will run when you run `unzip`.

The exact cause cannot be determined by this alone, but
1. If you're running command from `Git for Windows`, then use Command Prompt instead.
2. If you've not installed unzip to msys64, install `unzip` (see [Dockerfile](https://github.com/homuler/MediaPipeUnityPlugin/blob/92dd55579f2faeabf49338974ddb1d15ae54b683/docker/windows/x86_64/Dockerfile#L28))

**Comment by elfefe** [comment]
Hey when i'm trying to build i have this error:

`D:\Projets\Unity\MediaPipeUnityPlugin-0.6.2>C:/Python38/python build.py clean
Traceback (most recent call last):
  File "build.py", line 392, in <module>
    Argument().command().run()
  File "build.py", line 360, in __init__
    build_command_parser.add_argument('--resources', action=argparse.BooleanOptionalAction, default=True)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'`

**Comment by homuler** [comment]
Please use Python >= 3.9.0
https://github.com/homuler/MediaPipeUnityPlugin#prerequisites

**Comment by elfefe** [comment]
> Please use Python >= 3.9.0
> https://github.com/homuler/MediaPipeUnityPlugin#prerequisites

Indeed, my bad. Thanks you !

**Comment by wildfire2015** [comment]
win10 
the same error 
$ python build.py build --desktop cpu --include_opencv_libs -v
Loading:
Loading: 0 packages loaded
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/_bzl/2kbbcyl2/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
Analyzing: target //mediapipe_api:mediapipe_proto_srcs (0 packages loaded, 0 targets configured)
ERROR: D:/msys64/home/pq/mpp/WORKSPACE:302:23: fetching android_ndk_repository rule //external:androidndk: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1564776078 -0400"
DEBUG: Repository rules_python instantiated at:
  D:/msys64/home/pq/mpp/WORKSPACE:35:23: in <toplevel>
  C:/_bzl/2kbbcyl2/external/rules_pkg/deps.bzl:33:10: in rules_pkg_dependencies
  C:/_bzl/2kbbcyl2/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  C:/_bzl/2kbbcyl2/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Analysis of target '//mediapipe_api:mediapipe_proto_srcs' failed; build aborted: Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.
INFO: Elapsed time: 0.155s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel --output_user_root C:/_bzl build -c opt --action_env PYTHON_BIN_PATH=C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe //mediapipe_api:mediapipe_proto_srcs`
Traceback (most recent call last):
  File "D:\msys64\home\pq\mpp\build.py", line 392, in <module>
    Argument().command().run()
  File "D:\msys64\home\pq\mpp\build.py", line 109, in run
    self._run_command(self._build_proto_srcs_commands())
  File "D:\msys64\home\pq\mpp\build.py", line 51, in _run_command
    return subprocess.run(command_list, check=True)
  File "C:\Users\pq\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--output_user_root', 'C:/_bzl', 'build', '-c', 'opt', '--action_env', 'PYTHON_BIN_PATH=C://Users//pq//AppData//Local//Programs//Python//Python39//python.exe', '//mediapipe_api:mediapipe_proto_srcs']' returned non-zero exit status 1.

why window compiling need  Android NDK
but the doc don't have the step

**Comment by homuler** [comment]
@wildfire2015 

> Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME environment variable must be set.

I guess you've not set `ANDROID_NDK_HOME` properly.
