### ISSUE TITLE
Multiple Cameras and RTabmap?

### ISSUE THREAD

**Issue by TKTSWalker** [homuler/MediapipeUnityPlugin#311]
I'm going to be using this plugin as a driver for my smartglasses, is there any way to allow multiple cameras to run for the same scene? Also can RTabmap be used?

**Comment by homuler** [comment]
> is there any way to allow multiple cameras to run for the same scene?

`CalculatorGraph` receives images, not camera, so you can run multiple cameras.
Some graph may expect input images are from the same source — last detected landmarks are remembered sometimes ―, but in that case, you can run multiple `CalculatorGraph`s in a scene.

However, if you'd like to combine the results from multiple images (e.g. Triangulation), you need to do it by yourself because MediaPipe does not support it (AFAIK).

> Also can RTabmap be used?

I'm sorry I don' know, though it depends on use cases.
Please ask it in mediapipe's community.
