### ISSUE TITLE
example to send image to mediapipe

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#334]
hello
can you explane me how your project work with mediapipe core ?
for example
i have a texture2d (face image ) and want to send it to the mediapipe and will get list of the face landmarks point positions

can you help me how can i do it

or if the core (mediapipe) get OpenCV mat , how can i send a mat(BGR32 or ... ) to get face landmarks point positions from the Mat
( i seen your codes allot , but i fully confused and cant understand anything )

tnx

**Comment by homuler** [comment]
I'll document the details later, but here's the gist of it.
This plugin maps the API of MediaPipe to the API in C#, so that you can translate C++ code almost directly (Conversely, you need to know MediaPipe's API in order to understand the code).

The code related to FaceMesh is below.
- Code directly related to MediaPipe
   - [FaceMeshSolution](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Scenes/Face%20Mesh/FaceMeshSolution.cs): Main Program
   - [FaceMeshGraph](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Scenes/Face%20Mesh/FaceMeshGraph.cs): Class to run FaceMesh `CalculatorGraph`.
   - [GraphRunner](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs): `FaceMeshGraph`'s parent class.
- Code to convert Unity's Texture for MediaPipe
   - [Solution#ReadFromImageSource](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Common/Scripts/Solution.cs#L88-L108): `Solution` is a `FaceMeshSolution`'s parent class.
   - [TextureFrame](https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs): `Texture`'s wrapper class

Let's just take a closer look at the important parts.
The following code sends a `Texture` to MediaPipe.
https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Scenes/Face%20Mesh/FaceMeshSolution.cs#L124-L127

`textureFrame` is `TextureFrame`, which is implemented for sample app, but you can assume it is `Texture`.
If you'd like to use MediaPipe on a device other than Android, for now you need to convert the input image to a sequence of RGBA bytes, and this is done by following code (`GraphRunner#AddTextureFrameToInputStream`).
https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs#L163-L166
https://github.com/homuler/MediaPipeUnityPlugin/blob/2994e4425d347260006e15edc8d375e0d35a3b0f/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L234-L237

Note that you need to build an `ImageFramePacket` instance to send CPU image.

I recommend you compare the above code to the corrsponding C++ code.
https://github.com/google/mediapipe/blob/1faeaae7e504657f44544989f9547fc69652e487/mediapipe/examples/desktop/demo_run_graph_main.cc
