### ISSUE TITLE
New update with refine face landmarks meaning

### ISSUE THREAD

**Issue by FUBAR2077** [homuler/MediaPipeUnityPlugin#357]
@homuler I would like to ask what does new update bring? What refine_face_landmarks is responsible for?

**Comment by homuler** [comment]
In terms of functionality, `Refine Face Landmarks` is almost identical to the former `Detect Iris` option.
https://google.github.io/mediapipe/solutions/holistic.html#refine_face_landmarks

Setting it to `true`, the graph will return iris landmarks with (refined) face landmarks.

P.S. This option is actually not included in MediaPipe v0.8.8.
I mistakenly thought this feature had already been released (since Face Mesh's `refine_landmarks` option is already released), so I implemented it...

**Comment by FUBAR2077** [comment]
Ok, thank you for clarification :)
