### ISSUE TITLE
WebCam issue while building Standalone Application

### ISSUE THREAD

**Issue by Jay-artist** [homuler/MediaPipeUnityPlugin#401]
**Describe the feature and the current behavior/state.**
The webcam and media pipe work perfectly inside the unity editor but when I try to build it as a standalone PC application, the webcam does not work i.e. webcam doesn't get started. 
Please Guide me how to resolve this issue of webcam

**Comment by homuler** [comment]
Please use [build issue template](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-installation-issue.md).

At any rate, please check the log.
I guess it's caused by `DllNotFoundException` or something similar, in which case there have been a number of identical issues raised in the past.
