### ISSUE TITLE
FEATURE REQUEST: Issue labels or Issue naming system

### ISSUE THREAD

**Issue by Thomas-Boi** [homuler/MediaPipeUnityPlugin#404]
**Describe the feature and the current behavior/state.**
I recently ran into an error and I wanted to search for an existing Issue that might solves it. However, searching for it was difficult since there's no way to filter based on OS or what I used.

**Solution**
Perhaps a labelling system would be neat? Like if an Issue is about Windows and building for Android, it can contains the `window` and `android` labels. A naming system in the title could possibly work as well. 

**Additional context**
Add any other context here.

**Comment by homuler** [comment]
Rather than preparing naming conventions, I know I have to rewrite the title every time, but I haven't always been able to do it (after all, it's not enough to prevent people from creating the same issue repeatedly).

Since GitHub's label is functionally poor, I think it would be difficult to organize issues well, but if someone search them by label, I will consider using it properly.

For now, if you are looking for a way to fix an error, I think the best thing to do is to search by the error log.

**Comment by Thomas-Boi** [comment]
I see, that's fair no problem. Just a thought: you can specify a default title with [GitHub Issue Forms](https://github.com/devicons/devicon/issues/new?assignees=&labels=request%3Aicon&template=icon_request.yml&title=Icon+request%3A+%5BNAME%5D). That might help a bit differentiating build issues and running issues.

Thanks for the help though

**Comment by homuler** [comment]
Now I attached labels to most existing issues and rename some titles.

**Comment by Thomas-Boi** [comment]
Thank you for your work 😄
