### ISSUE TITLE
Aligned 3d Face model with the detected face landmarks (3d points)

### ISSUE THREAD

**Issue by am-badshah** [homuler/MediaPipeUnityPlugin#410]
Is there anyone who implemented or added a face model like glasses or Mask to the detected 3d face landmarks? or if anyone can point to a link or thread where we can study about implementing it ourselves?

thank you

**Comment by homuler** [comment]
related to #79

**Comment by am-badshah** [comment]
@homuler as you mention that Packet<Mesh3d> class is not implemented yet and you planned to implement a sample soon. is there anything done related to it?

**Comment by homuler** [comment]
I implemented `Packet<Mesh3d>` class once in a working branch, but did not merge it to the master branch because I found it unnecessary.
After all, if you don't create a Mesh in Unity, it's not useful.

> or if anyone can point to a link or thread where we can study about implementing it ourselves?

https://github.com/keijiro/FaceMeshBarracuda
https://github.com/keijiro/FaceLandmarkBarracuda/blob/0ff22f2ecbd2d73e8e04bb7dc3bd1649f5942ae7/Assets/Editor/TemplateBuilder.cs

By the way, is it same as #79?
If so, I'd like to close this.

**Comment by am-badshah** [comment]
Thank you. I will have a look at the FaceMeshBarracude. 
I was actually trying to add some overlay filters models like ears and nose or glasses. 
[https://developers.google.com/ar/develop/augmented-faces](url).

i am not sure if creating a Mesh will help me with it.

**Comment by homuler** [comment]
Closing because it's same as #79
