### ISSUE TITLE
Error in make android_arm64

### ISSUE THREAD

**Issue by jsaon-L** [homuler/MediaPipeUnityPlugin#42]
i run `make android_arm64` in `MediaPipe Unity Plugin`   get error
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
ljl@ljl-B460MAORUSELITE:~/Downloads/MediaPipeUnityPlugin$ make android_arm64
cd C && bazel build -c opt --config=android_arm64 mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android mediapipe_api:mediapipe_models mediapipe_api:mediapipe_proto_srcs
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a0f90646527c4e7222f7f2b29042a8f23d81996d8509e7ccd21c36a247348eb1"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/ljl/Downloads/MediaPipeUnityPlugin/C/WORKSPACE:79:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/3bf2eb8198ff65c00b4c1c6bf4ce01f7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Build options --cpu and --fat_apk_cpu have changed, discarding analysis cache.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6"
DEBUG: Repository rules_cc instantiated at:
  /home/ljl/Downloads/MediaPipeUnityPlugin/C/WORKSPACE:73:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/3bf2eb8198ff65c00b4c1c6bf4ce01f7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target //mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 0.075s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 40 targets con\
figured)
    currently loading: @rules_pkg//
    Fetching ...python; Cloning 4b84ad270387a7c439ebdccfd530e2339601ef27 of ht\
tps://github.com/bazelbuild/rules_python.git
Makefile:48: recipe for target 'android_arm64' failed
make: *** [android_arm64] Error 1

--------------------------------------------------------------------------------

i use setup_android_sdk_and_ndk.sh https://github.com/google/mediapipe/blob/master/setup_android_sdk_and_ndk.sh

i can run mediapipe android command
↓↓↓↓↓↓↓↓↓↓↓
`bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`

ljl@ljl-B460MAORUSELITE:~/Downloads/mediapipe-0.8.2$ bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a0f90646527c4e7222f7f2b29042a8f23d81996d8509e7ccd21c36a247348eb1"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/ljl/Downloads/mediapipe-0.8.2/WORKSPACE:39:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/c7df26029a2a82fe2e630be26bc9cc65/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6"
DEBUG: Repository rules_cc instantiated at:
  /home/ljl/Downloads/mediapipe-0.8.2/WORKSPACE:33:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/c7df26029a2a82fe2e630be26bc9cc65/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'android_opencv' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "cdb0e190c3734edd4052a3535d9e4310af912a9f70a421b1621711942a1028d5"
DEBUG: Repository android_opencv instantiated at:
  /home/ljl/Downloads/mediapipe-0.8.2/WORKSPACE:221:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ljl/.cache/bazel/_bazel_ljl/c7df26029a2a82fe2e630be26bc9cc65/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_deploy.jar
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk
INFO: Elapsed time: 0.215s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

---------------------------------------------------------------------------------------

**Comment by jsaon-L** [comment]
Ubuntu 18.04.5 LTS

i can run 
```
Desktop GPU (Linux only)
make
make install
```
and run whit UnityEditor

**Comment by homuler** [comment]
Maybe the same problem as https://github.com/homuler/MediaPipeUnityPlugin/issues/35 .
Which version of `gcc` and `g++` do you use?

**Comment by jsaon-L** [comment]
> Maybe the same problem as #35 .
> Which version of `gcc` and `g++` do you use?

`gcc -v` get `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) `
`g++ -v` get `gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) `

my console

```
ljl@ljl-B460MAORUSELITE:~/Downloads/MediaPipeUnityPlugin$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```

**Comment by homuler** [comment]
Will you tell me the output of the below commands?
```sh
bazel --version
ls $ANDROID_HOME
ls $ANDROID_NDK_HOME
```

And I'd also like to know whether you can build an official apk after running `bazel clean --expunge`.
```sh
bazel clean --expunge
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
```

**Comment by jsaon-L** [comment]
> Will you tell me the output of below commands?
> 
> ```shell
> bazel --version
> ls $ANDROID_HOME
> ls $ANDROID_NDK_HOME
> ```
> 
> And I'd also like to know whether you can build an official apk after running `bazel clean --expunge`.
> 
> ```shell
> bazel clean --expunge
> bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
> ```

sorry
i dont know why i lost ndk dir
Now I'm going to the hospital
see you tomorrow

**Comment by AhmedEmadEldinHussin** [comment]
when I write this command
ls $ANDROID_HOME
it list the files in directory

**Comment by homuler** [comment]
Then please set `ANDROID_HOME` and `ANDROID_NDK_HOME` first.
https://google.github.io/mediapipe/getting_started/android.html#prerequisite

**Comment by AhmedEmadEldinHussin** [comment]
okay   I did it 
when i make
ls $ANDROID_HOME
this is the result
and when i make  
ls $ANDROID_NDK_HOME
build         ndk-gdb    NOTICE            python-packages  source.properties
CHANGELOG.md  ndk-lldb   NOTICE.toolchain  README.md        sources
meta          ndk-stack  package.xml       shader-tools     toolchains
ndk-build     ndk-which  prebuilt          simpleperf       wrap.sh

then it is the results when i run this command
make android_arm64


mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0    351      0 --:--:-- --:--:-- --:--:--   350
100 5154k    0 5154k    0     0  3030k      0 --:--:--  0:00:01 --:--:-- 5737k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
./.build/protobuf-3.13.0/csharp/buildall.sh
+ echo Building relevant projects.
Building relevant projects.
+ dotnet restore ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
  Determining projects to restore...
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/AddressBook.csproj (in 259 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj (in 259 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj (in 285 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/Google.Protobuf.csproj (in 289 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj (in 342 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj (in 400 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj (in 401 ms).
+ dotnet build -c Release ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard1.1/Google.Protobuf.dll
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf.JsonDump -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/bin/Release/netcoreapp2.1/Google.Protobuf.JsonDump.dll
  AddressBook -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/bin/Release/netcoreapp2.1/AddressBook.dll
  Google.Protobuf.Benchmarks -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/bin/Release/netcoreapp3.1/Google.Protobuf.Benchmarks.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/net45/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard1.1/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/net451/Google.Protobuf.Test.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
  Google.Protobuf.Conformance -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/bin/Release/netcoreapp2.1/Google.Protobuf.Conformance.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.25
+ echo Running tests.
Running tests.
+ dotnet test -c Release -f netcoreapp2.1 ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
Test run for /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll (.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:  1124, Skipped:     0, Total:  1124, Duration: 9 s - /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll (netcoreapp2.1)
cd C && bazel build -c opt --config=android_arm64 mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android mediapipe_api:mediapipe_models mediapipe_api:mediapipe_proto_srcs
Starting local Bazel server and connecting to it...
ERROR: While resolving toolchains for target //mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android_android_lib: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 3.054s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 117 targets c\
onfigured)
make: *** [Makefile:52: android_arm64] Error 1

**Comment by homuler** [comment]
Did you set `ANDROID_HOME` ? (and I'd like to know the value of `ANDROID_NDK_HOME`, maybe the version is too new)
```sh
echo $ANDROID_HOME
echo $ANDROID_NDK_HOME
```

And can you build MediaPipe official apks? (e.g. `bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`)
If not, I strongly recommend you should build an official apk first.

**Comment by AhmedEmadEldinHussin** [comment]
this is the value of ANDROID_HOME
/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk
this is the value echo $ANDROID_NDK_HOME
/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk/ndk/22.0.7026061

and when i tried to build the official apk it didnt hasnt built also

**Comment by AhmedEmadEldinHussin** [comment]
and this is the log for it also may it help 


ERROR: Error fetching repository: java.io.IOException: The repository's path is "/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk" (absolute: "/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk") but a symlink could not be created for it, because: /home/kitmek/Android/Sdk/home/kitmek/Android/Sdk (No such file or directory)
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: The repository's path is "/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk" (absolute: "/home/kitmek/Android/Sdk/home/kitmek/Android/Sdk") but a symlink could not be created for it, because: /home/kitmek/Android/Sdk/home/kitmek/Android/Sdk (No such file or directory)
INFO: Elapsed time: 0.182s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: @rules_foreign_cc//tools/build_defs/shell_toolchain/too\
lchains ... (4 packages)
    Fetching @local_config_sh; fetching

**Comment by AhmedEmadEldinHussin** [comment]
what is the version of android sdk and ndk you used for it then i can also downgrade if it is possible

**Comment by homuler** [comment]
Please read the log, your `ANDROID_HOME` must be wrong.

> /home/kitmek/Android/Sdk/home/kitmek/Android/Sdk (No such file or directory)

Maybe `/home/kitmek/Android/Sdk` ?
And with NDK version 22, it may fail to build (but not relevant to the above error).
NDK version 21 is OK.

**Comment by AhmedEmadEldinHussin** [comment]
after restarting the pc this error has been removed and it returned this erro when building the apk 


bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
Starting local Bazel server and connecting to it...
Loading: 0 packages loaded
    Fetching @bazel_skylib; fetching
    Fetching /home/kitmek/.cache/bazel/_bazel_kitmek/35c4330a980a6ba06cfd6fda0INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip) = 84bd904073d5a04bfb746284edf9afbd840f9953b4188614876cd331439d5121
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "84bd904073d5a04bfb746284edf9afbd840f9953b4188614876cd331439d5121"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/kitmek/mediapipe/WORKSPACE:39:13: in <toplevel>
Repository rule http_archive defined at:
  /home/kitmek/.cache/bazel/_bazel_kitmek/35c4330a980a6ba06cfd6fda00a7a779/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = b997139e841ca8bada561686f403dc06f6b9dc64b32ac155152688f2f9ad2101
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "b997139e841ca8bada561686f403dc06f6b9dc64b32ac155152688f2f9ad2101"
DEBUG: Repository rules_cc instantiated at:
  /home/kitmek/mediapipe/WORKSPACE:33:13: in <toplevel>
Repository rule http_archive defined at:
  /home/kitmek/.cache/bazel/_bazel_kitmek/35c4330a980a6ba06cfd6fda00a7a779/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: While resolving toolchains for target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 6.994s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 39 targets configured)

**Comment by homuler** [comment]
What are the current values of `ANDROID_HOME` and `ANDROID_NDK_HOME`?

**Comment by AhmedEmadEldinHussin** [comment]
I think it is going to be built I downgraded android ndk to the version you mentioned ,  
now iam building the apk as ane xperiment as you mentioned 
it  is fetching some files from gtihub



export ANDROID_HOME=/home/kitmek/Android/Sdk/
![Screenshot from 2021-02-04 11-33-22](https://user-images.githubusercontent.com/18230011/106859711-d5c18580-66dc-11eb-9bb5-5728486ff94c.png)

**Comment by AhmedEmadEldinHussin** [comment]
the apk has been built fine with out any problem after 45 minutes 
but still the problem happens when i try to build the plugin

these are the values 
echo $ANDROID_HOME
/home/kitmek/Android/Sdk/
echo $ANDROID_NDK_HOME
/home/kitmek/Android/Sdk/ndk/21.0.6011959
 and this is the log message 


ake android_arm64
mkdir -p .build
curl -L https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz -o .build/protobuf-3.13.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133    0   133    0     0    160      0 --:--:-- --:--:-- --:--:--   160
100 5154k    0 5154k    0     0   990k      0 --:--:--  0:00:05 --:--:-- 1350k
tar xf .build/protobuf-3.13.0.tar.gz -C .build
./.build/protobuf-3.13.0/csharp/buildall.sh
+ echo Building relevant projects.
Building relevant projects.
+ dotnet restore ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
  Determining projects to restore...
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/AddressBook.csproj (in 273 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj (in 273 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj (in 299 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/Google.Protobuf.csproj (in 299 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj (in 358 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj (in 372 ms).
  Restored /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj (in 373 ms).
+ dotnet build -c Release ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.sln
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/net45/Google.Protobuf.dll
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard1.1/Google.Protobuf.dll
  Google.Protobuf.JsonDump -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.JsonDump/bin/Release/netcoreapp2.1/Google.Protobuf.JsonDump.dll
  AddressBook -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/AddressBook/bin/Release/netcoreapp2.1/AddressBook.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/net45/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Benchmarks -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Benchmarks/bin/Release/netcoreapp3.1/Google.Protobuf.Benchmarks.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard1.1/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/net451/Google.Protobuf.Test.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
  Google.Protobuf.Conformance -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Conformance/bin/Release/netcoreapp2.1/Google.Protobuf.Conformance.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.16
+ echo Running tests.
Running tests.
+ dotnet test -c Release -f netcoreapp2.1 ./.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Google.Protobuf -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf/bin/Release/netstandard2.0/Google.Protobuf.dll
  Google.Protobuf.Test.TestProtos -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test.TestProtos/bin/Release/netstandard2.0/Google.Protobuf.Test.TestProtos.dll
  Google.Protobuf.Test -> /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll
Test run for /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll (.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:  1124, Skipped:     0, Total:  1124, Duration: 8 s - /home/kitmek/MediaPipeUnityPlugin/.build/protobuf-3.13.0/csharp/src/Google.Protobuf.Test/bin/Release/netcoreapp2.1/Google.Protobuf.Test.dll (netcoreapp2.1)
cd C && bazel build -c opt --config=android_arm64 mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android mediapipe_api:mediapipe_models mediapipe_api:mediapipe_proto_srcs
Starting local Bazel server and connecting to it...
ERROR: While resolving toolchains for target //mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android_dummy_app: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
ERROR: Analysis of target '//mediapipe_api/java/org/homuler/mediapipe/unity:mediapipe_android' failed; build aborted: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
INFO: Elapsed time: 3.169s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded, 117 targets c\
onfigured)
make: *** [Makefile:52: android_arm64] Error 1

**Comment by homuler** [comment]
Ok, will you continue in your own issue? #48

**Comment by AhmedEmadEldinHussin** [comment]
I think it is solved 
if found the solution now I have to export those values in the terminal session before building 
so it is building now 
![Screenshot from 2021-02-04 12-28-59](https://user-images.githubusercontent.com/18230011/106865443-a44cb800-66e4-11eb-8bd1-b24b5986423a.png)

**Comment by AhmedEmadEldinHussin** [comment]
it is already built now thank you
![Uploading Screenshot from 2021-02-04 12-31-10.png…]()
