### ISSUE TITLE
Directly using the pointer of source texture 

### ISSUE THREAD

**Issue by grayhong** [homuler/MediaPipeUnityPlugin#435]
### Description

Hi Homuler! Thank you so much for the amazing work!

I'm using your UnityPlugin in my Android project and want to improve the performance to support low-end devices.

While I was profiling my Unity project with Android target, I found that the function `ReadFromImageSource` takes quite long (~7ms).  (FYI. I am using `HolisticTracking` model)

Since I am using AR Camera as well, I had to use `Texture` as a source of `TextureFrame`.

I found that in a `TextureFrame`, it copies the source texture to the `TextureFrame`'s texture and then hand over the pointer to the gpu through `GlTextureBuffer`

https://github.com/homuler/MediaPipeUnityPlugin/blob/ea587cfbfece8c76ae5755eab9c0bbde1b9b3bce/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L136-L140

https://github.com/homuler/MediaPipeUnityPlugin/blob/ea587cfbfece8c76ae5755eab9c0bbde1b9b3bce/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L341-L364

However, since I already had the `Texture`, I thought copying the texture again is unnecessary.  
So, I tried to use `texture.GetNativeTexturePtr()` directly as a `target` argument of `GlTextureBuffer`, but it didn't work.

So my question is, **is it possible to directly use the `Texture`'s pointer as an input of `GlTextureBuffer` without copying to the `TextureFrame`'s texture?** 

I suspect that there should be a reason you did `GetPixel32` and `SetPixel32` , could you explain it?

Thank you so much for your time!

**Comment by homuler** [comment]
> is it possible to directly use the Texture's pointer as an input of GlTextureBuffer without copying to the TextureFrame's texture?

It's a bit difficult to answer while I don't know what does not work how.
As you've probably noticed, when the graphics API is OpenGL ES, `Texture`'s pointer is already passed to `GlTextureBuffer` directly (`TextureFrame#GetTextureName` returns it).
https://github.com/homuler/MediaPipeUnityPlugin/blob/c4de7fdb4b5e073e2a6320811fb52a10189e1746/Assets/Mediapipe/Samples/Common/Scripts/GraphRunner.cs#L157-L161
https://github.com/homuler/MediaPipeUnityPlugin/blob/c4de7fdb4b5e073e2a6320811fb52a10189e1746/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L222

I think what you really want to know is why `Texture` is _copied_ on _CPU_ (in the sample app), and if it can be avoided in your case. And maybe it's related to the below question.

> I suspect that there should be a reason you did GetPixel32 and SetPixel32 , could you explain it?

### Why Texture is Copied?
It's because the sample app does not manage the source texture (e.g. OpenGL texture that `WebCamTexture` uses internally).
As a result, when MediaPipe try to read the (OpenGL) texture, which we pass by its name, the corresponding (GPU) memory may already be freed.
So if you can control when the (OpenGL) texture is freed, you don't need to copy the source `Texture`.

### Why Texture is Copied on _CPU_?
Actually, it's not necessary, and you can copy it on GPU, but in that case, the input (image) and the output can be out of sync.
See https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-961018299 for more details (the 1st comment is correct).

You can test it by calling `ReadTextureFromOnGPU` in place of `ReadTextureFromOnCPU` (though it's not perfectly implemented and tested well). Please note that it only works on Android.
https://github.com/homuler/MediaPipeUnityPlugin/blob/c4de7fdb4b5e073e2a6320811fb52a10189e1746/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs#L112-L119
https://github.com/homuler/MediaPipeUnityPlugin/blob/c4de7fdb4b5e073e2a6320811fb52a10189e1746/Assets/Mediapipe/Samples/Common/Scripts/Solution.cs#L77-L82

**Comment by grayhong** [comment]
Thank you so much for the quick reply! I really appreciate it.

> So if you can control when the (OpenGL) texture is freed, you don't need to copy the source Texture.  

I guess this would be very hard,, Now I understand why you copied a texture.

I tried to use CopyTexture, but I've got an error that the input source (AR Camera)'s texture and the `TextureFrame`'s texture have different input dimensions. 
`Graphics.CopyTexture called with mismatching texture sizes (src 1440x1080x1 dst 1080x1440x1)`
To solve this, I could do `Graphics.CopyTexture` after calling a `Graphics.Blit()`. I have no idea why `Graphics.Blit()` solves the dimension mismatching issue, but it worked.

However, `Blit()` seems unnecessary to me, and as you expected, the Mediapipe output was not in a sync with the camera input.

Anyways, thank you so much for the advice and I will let you know if I find an efficient way to bypass the `SetPixel()` call!

**Comment by homuler** [comment]
> `Graphics.CopyTexture called with mismatching texture sizes (src 1440x1080x1 dst 1080x1440x1)`

Aren't `textureWidth` and `textureHeight` reversed?
https://github.com/homuler/MediaPipeUnityPlugin/blob/c4de7fdb4b5e073e2a6320811fb52a10189e1746/Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs#L128

**Comment by grayhong** [comment]
Yes! But I think it is issue in the AR camera (the camera source that I'm currently using). It's width and height are flipped by some reason. Thank you for checking!
