### ISSUE TITLE
Knift support in unity

### ISSUE THREAD

**Issue by Akri** [homuler/MediaPipeUnityPlugin#444]
### Feature Description

I would like to run the Knift example from the original mediapipe project in unity; are there plans to add this in the forseeable future?
i tried it myself, but failed due to lacking understanding of the whole solution.  

### Current Behaviour/State

After building the cloned project with bazel, I added the knift graph to the unity project, and built the necessary .tflite and .pb files with the original mediapipe project (and put the into the streaming assets folder); when  i try to start a scene including the graph i get the error: "MediaPipeException: FAILED_PRECONDITION: Mediapipe.MediaPipeException: Failed to parse config text. See error logs for more details" - i cant find any error logs.
Im pretty sure this error is related to my knift_cpu.txt graph, but i dont know whats wrong with it

**Comment by homuler** [comment]
>  i cant find any error logs.

If you're running in the sample project, please check Editor.log.
If you prefer, you can validate the graph config using the official sample code (in C++).

> are there plans to add this in the forseeable future?

I've received some requests (#29), but I haven't decided whether to add the sample scene.
If there are missing APIs to run KNIFT, I'll support them, but otherwise, it's not a high priority.

**Comment by Zumbalamambo** [comment]
+1

**Comment by homuler** [comment]
closes since the KNIFT support has ended.
cf. https://github.com/google/mediapipe/blob/master/docs/solutions/knift.md
