### ISSUE TITLE
Git LFS support on forks

### ISSUE THREAD

**Issue by Neleac** [homuler/MediaPipeUnityPlugin#475]
### Feature Description

Requesting enabling Git LFS on forks by adding an LFS object to the upstream repo. This has to be done from the original repo instead of through a pull request. See [this comment](https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273) for more detailed explanation.

### Current Behaviour/State

<img width="526" alt="Capture" src="https://user-images.githubusercontent.com/31634644/156453095-5956e358-c3c3-4673-b46c-897a3cf2027a.PNG">

Currently we cannot use Git LFS on forks, because the upstream repo does not have LFS objects.

### Additional Context

Git LFS is essential for Unity development. Supporting Git LFS on forks will greatly benefit developers using this repo. Thank you!

**Comment by homuler** [comment]
> Git LFS is essential for Unity development.

I understand you'd like to enable Git LFS on _your_ project, but I can't think of a use case for _this_ project other than to push a few libraries (cf. #407)
Will you tell me why it's essential for this project?

P.S.
I think it's difficult to use Git LFS on public repositories owned by a personal account, given GitHub's billing structure, since any malicious users could easily use up the owner's bandwidth, which may be one of the reasons why GitHub limits the use of LFS.
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#tracking-storage-and-bandwidth-use

**Comment by Neleac** [comment]
My bad. I didn't know LFS on forks counts towards the _original_ repo owner's quota.
