### ISSUE TITLE
How to get facepose transform matrix

### ISSUE THREAD

**Issue by Hakazaba** [homuler/MediaPipeUnityPlugin#481]
### Plugin Version or Commit ID

v0.83

### Unity Version

2020.3.8f1

### Your Host OS

Ubuntu 18.04

### Target Platform

Linux Standalone

### Description

I am currently trying to figure out how to return the face pose transformation matrix but im not sure how. [According to this] (https://github.com/google/mediapipe/issues/1561) it's calculated by mediapipe, but im not sure how to get it through the mediapipe unity plugin. Can i please have some help with this?

**Comment by homuler** [comment]
I have confirmed in the past that I could get `FaceGeometryPipelineCalculator` to work, but it doesn't work as it is and some manual work is required (e.g. build [`geometry_pipeline_metadata.binarypb`](https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/modules/face_geometry/face_geometry.pbtxt#L45)).

If necessary, you can convert this issue to a feature request.

P.S. Another option is to implement it in C#.
https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L309-367

**Comment by sassa4771** [comment]
@homuler 
First of all, thank you for creating this wonderful asset.

@Hakazaba 
I am sharing this because I faced the same problem and finally found a solution.
The method of 3D facepose estimation using Landmark generally uses PnP, a method of estimating 3D coordinates from 2D coordinates.
OpenCV has the method called "solvePnP" to do this calculation, so it was possible to create a PnP code by yourself.
https://docs.opencv.org/4.x/d5/d1f/calib3d_solvePnP.html

In Unity, OpenCV is available as an asset called OpenCVforUnity, and you can reproduce the 3D facepose estimation by referring to FaceTrackingExample in this asset.(It has even been confirmed to work on the iPhone.)
https://assetstore.unity.com/packages/templates/tutorials/facetracker-example-35284#content

**Comment by dayowoo** [comment]
@homuler 
I found #671 . 
After adding the `geometry_pipeline.cipeline.cc` below to `mediapipe_api/modules/face_geometry/protos/face_goemetry.cc`, I want to build it, is this the right way? If it's wrong, I'll try another way.
Thank you for the great project.

> P.S. Another option is to implement it in C#. https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/modules/face_geometry/libs/geometry_pipeline.cc#L309-367

**Comment by dayowoo** [comment]
@homuler
Hello, Can I ask you to explain how to build the file in this project.
Thank you for the great project.


> (e.g. build [geometry_pipeline_metadata.binarypb](https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/modules/face_geometry/face_geometry.pbtxt#L45)).
