### ISSUE TITLE
Hand Tracking flickering for more than one hand

### ISSUE THREAD

**Issue by Densen90** [homuler/MediaPipeUnityPlugin#491]
### Description

Hi there,

I used an older version (I think around mid last year) of your project for hand tracking where everything worked fine. After updating to the current version (0.8.3) I found that there are some problems with detecting more than one hand.

When max num of hands is set to 1, everything works fine. When setting it to 2 or 3, it takes long until one hand is detected and for both hand it is flickering a lot, where the hand gets detected and lost frequently.

Do you know how I could fix that?

Thanks and all the best.

**Comment by homuler** [comment]
Are you talking about the sample app?
If so, how about running in synchronous mode? (https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-932074718)

**Comment by homuler** [comment]
> But then my framerate drops from 130 to 20.

Was the frame rate better before?

> The curious thing is, that the flickering only occurs when there are less hands visible than set in max_hands.

The reason why flickering occurs is that MediaPipe may return empty packets even when hands are present in the input image (the sample app is implemented in such a way that those empty packets are dropped until the timeout period elapses).
This situation changes when `max_hands` hands are detected because `HandLandmarkTrackingGpu`/`HandLandmarkTrackingCpu` won't try detecting new palms anymore.
https://github.com/google/mediapipe/blob/4de382d6f6446089f047d799595d4179953de835/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt#L88-L101
