### ISSUE TITLE
DllNotFoundException: mediapipe_c

### ISSUE THREAD

**Issue by davimedio01** [homuler/MediaPipeUnityPlugin#492]
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2020.3.30f1

### Your Host OS

Windows 11 Home

### Target Platform

Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

Visual Studio C++: 14.16.27023
Windows SDK: 10.0.19041.685

### Command Sequences

Comands for Build with Docker Engine v20.10.12 and Docker Desktop 4.5.1 (74721):

```
Rem Build a Docker image from Dockerfile in project folder
docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile
```
---------------------------------------------------------------------------------------------------------
```
Rem Run with `Packages` directory mounted to the container
Rem Specify `--cpus` and `--memory` options according to your machine.
docker run --cpus=8 --memory=12g ^
    --mount type=bind,src=%CD%\Packages,dst=/home/mediapipe/Packages ^
    --mount type=bind,src=%CD%\Assets,dst=/home/mediapipe/Assets ^
    -it mediapipe_unity:linux
```
---------------------------------------------------------------------------------------------------------
```
Rem Inside Docker, build OpenCV from sources for Desktop and build for Android
python build.py build --desktop gpu --opencv cmake -vv
python build.py build --android arm64 -vv
```

### Log

[log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/8249277/log.txt)

### Additional Context

I check every solution in troubleshooting page, but nothing related with "mediapipe_c"...
Below, is the Unity screenshot after enter Play Mode, with the Docker shutdown!

![Screenshot_2022-03-14_21-09-12](https://user-images.githubusercontent.com/50346745/158281493-efdffab3-2645-48fc-939e-5f219b8f23eb.png)

I tried running the "build" command for Android and gave me same error. After this, I tried run the "build" command with OpenCV argument, and Android build after, but same problem...

**Comment by homuler** [comment]
https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container
> > :warning: This can be used only to build libraries for _Android_ and you cannot build libraries for _Windows_.
So you cannot build the native library for Windows, that is, for UnityEditor.

Please follow https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#windows-10 to build `mediapipe_c.dll`.

**Comment by LGuilhermeRodrigues** [comment]
I got the same DllNotFoundException here today on a windows 11 machine even with mediapipe_c.dll correctlly built (without docker) and set to load at startup.

Then I have used the ldd command and noticed VCRUNTIME140_1.dll was missing on my computer. So I installed microsoft visual c++ and the problem is solved.

It think it's not relatable to the issue @davimedio01 but can help other with the same error code

**Comment by davimedio01** [comment]
Wait, so how could I use the plugin on my Unity on Windows to build Android-**only** applications? I'm a little confused now, because I thought that Docker was used to perform the build in a virtual machine and use the compiled ones on the host machine... but I think I must be wrong.
Anyway, would it be a better idea to use an ArchLinux based distro (like Manjaro) to use the plugin in Unity?

Anyway, thank you both so much!!

**Comment by homuler** [comment]
Simply put, the plugin does not work on your UnityEditor because `mediapipe_c.dll` is not built (`libmediapipe_c.so` might have been built, but it's not compatible with Windows).

To run this plugin on Android, you need to build `mediapipe_android.aar`, which contains `libmediapipe_c.so` (built for armv7 or arm64).
You can build `mediapipe_android.aar` using Linux, macOS, Docker Linux Container, or Docker Windows Container.
But this `libmediapipe_c.so` does not work on Windows, since the Windows loader does not support the format, and also its target architecture is different (x86-64 vs armv7 or arm64).

So even if you want to build _Android-only_ applications and don't need to support _PC Standalone_, as far as you'd like to run it on UnityEditor, you still need to build a native library for Windows (`mediapipe_c.dll`).
The point is that `mediapipe_c.dll` can only be built on Windows OS (note that `libmediapipe_c.so` will be built when you run the build command on Docker Linux Container), and this is what I meant at https://github.com/homuler/MediaPipeUnityPlugin/issues/492#issuecomment-1067469558.
