### ISSUE TITLE
How to use our MediaPipe calculators and TFLite models in Unity

### ISSUE THREAD

**Issue by ahmethaydarornek** [homuler/MediaPipeUnityPlugin#495]
### Plugin Version or Commit ID

v0.8.2

### Unity Version

2020.3.30f1

### Your Host OS

macOS M1

### Target Platform

UnityEditor

### Description

I've built the MediaPipeUnityPlugin and run succesfully in Unity. 
Now I want to build the MediaPipeUnityPlugin with my calculators.
I have calculators and tflite models different from the original MediaPipe repo. 
My question is how to use our calculators (i.e. our MediaPipe repositories) while building the plugin.

**Comment by homuler** [comment]
Please read https://github.com/homuler/MediaPipeUnityPlugin/issues/242#issuecomment-900249401 and https://github.com/homuler/MediaPipeUnityPlugin/issues/277#issuecomment-921433238.

> There are 2 ways to achieve this.
>    1. Fork mediapipe and pull it in place of the original repository.
>    1. Create files under mediapipe_api and apply patch files if necessary (just like this plugin does).

In the former case, you need to switch `mediapipe` repository's URL to yours.
https://github.com/homuler/MediaPipeUnityPlugin/blob/42106737e3d4b57efddd2e4d8e646b7b8e283fba/WORKSPACE#L76

However, I recommend the latter method if possible, since you may have to modify the [patch files](https://github.com/homuler/MediaPipeUnityPlugin/blob/42106737e3d4b57efddd2e4d8e646b7b8e283fba/WORKSPACE#L66-L73) by yourself when they conflict with your changes.

In any way, please read the above comments and if you have any questions, please ask.

**Comment by ahmethaydarornek** [comment]
I'm trying to switch mediapipe repository's URL to mine. I created a new release including my changes (https://github.com/ahmethaydarornek/mediapipe/archive/v0.8.9.10.tar.gz). 

<img width="635" alt="image" src="https://user-images.githubusercontent.com/23193213/158768115-1208be54-82f9-4482-b4b1-94bdedc5fa39.png">

The problem is that Prefix "mediapipe-0.8.9.10" could not be found in the archive. Error message:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/23193213/158768771-fdefacc5-07df-475c-a2fd-4021aee27b58.png">

**Comment by homuler** [comment]
You must change sha256, too.
Otherwise, the cached file will be reused.

**Comment by ahmethaydarornek** [comment]
Which directory should I use to create sha256? I'm very new about bazel workspace. 

I've tried the following command but it gives the same sha256 ("54ce6da9f167d34fe53f928c804b3bc1fd1dd8fe2b32ca4bf0b63325d34680ac")
shasum -a 256 /private/var/tmp/_bazel_ahmethaydarornek/db66cf427f2cddd2341b41874f0fe701/external/com_google_mediapipe/temp3958638767779553797/v0.8.9.10.tar.gz

**Comment by homuler** [comment]
> I'm very new about bazel workspace.

Well, I think you should read the official document first.
If you really don't care, remove the `sha256` attribute and try again. Bazel will download the target file and tell you the sha256 value (if the content has not been tampered with).

**Comment by ahmethaydarornek** [comment]
Thanks for your helps. The following command also gives the sha256:

`curl -L https://github.com/ahmethaydarornek/mediapipe/archive/v0.8.9.10.tar.gz | sha256sum`
