### ISSUE TITLE
just following wiki, but stuck in docker install process. 

### ISSUE THREAD

**Issue by kotran88** [homuler/MediaPipeUnityPlugin#500]
### Plugin Version or Commit ID

v.0.8.2

### Unity Version

2020.3.30f1

### Your Host OS

Monterrey 12.3

### Target Platform

Android

### Command Sequences

docker run \                                      
    --mount type=bind,src=$PWD/Packages,dst=/home/mediapipe/Packages \
    --mount type=bind,src=$PWD/Assets,dst=/home/mediapipe/Assets \
    -it mediapipe_unity:latest

### Log

I clone repo directory and on there, I commanded all line that is wiki says. 

I choose ubuntu 
docker build --build-arg UID=$(id -u) -t mediapipe_unity:latest . -f docker/linux/x86_64/Dockerfile.ubuntu
after above command

then, I login with command docker login. 

and , I commanded

docker run \
    --mount type=bind,src=$PWD/Packages,dst=/home/mediapipe/Packages \
    --mount type=bind,src=$PWD/Assets,dst=/home/mediapipe/Assets \
    -it mediapipe_unity:latest

it cause error 
`
docker: Error response from daemon: Get "http://ipc/registry/access": dial unix /Users/pedrojung/Library/Containers/com.docker.docker/Data/backend.sock: connect: connection refused.`

and..I can't find  file on path  described. 
/Users/pedrojung/Library/Containers/com.docker.docker/Data/backend.sock

the problem is... I'm new to docker, so , after installing docker desktop, I didn't do anything with docker . is it right? 
on wiki, it doesn't say anything to do with docker except for command lines. 

I configured ANDROID_HOME and ANDROID_NDK_HOME both
```
pedrojung@pedroui-MacBookPro MediaPipeUnityPlugin-master2 % echo $ANDROID_HOME                                      
/Users/pedrojung/Library/Android/sdk
pedrojung@pedroui-MacBookPro MediaPipeUnityPlugin-master2 % echo $ANDROID_NDK_HOME
/Users/pedrojung/Library/Android/sdk/ndk
```

**Comment by homuler** [comment]
Well, you say "just following wiki", but I believe there's no description how to build libraries using Docker on macOS, since it's not supported (so please use a Windows or Linux machine).
However, I confirmed that it works on my mac (intel), so I'll update the document later.

If you don't know how to run Docker, please ask it elsewhere (e.g. StackOverflow).
Maybe https://github.com/docker/for-mac/issues/4768#issuecomment-770772341 will be helpful.

P.S.
You don't need to set environment variables when running Docker containers, since they do not affect.
In addition to that, I guess your `ANDROID_NDK_HOME` is wrong in the first place (usually it looks like`/Users/xxx/Library/Android/sdk/ndk/21.0.xxxx`).
