### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by souravrs999** [homuler/MediaPipeUnityPlugin#52]
Request for a proper documentation it would be very helpful.

**Comment by homuler** [comment]
What kind of documents do you want? (e.g. C# API usage, how to add native APIs, etc...)

**Comment by souravrs999** [comment]
Anything would be helpful, classes, functions, APIs etc

**Comment by Hakazaba** [comment]
I would like to know how to get nodes as a 3D position rather than a normalized vector

**Comment by homuler** [comment]
@Hakazaba Do you mean that you'd like to know how to convert normalized values such as `NormalizedLandmark#x, y, z` into the position in Unity's coordinate system?

**Comment by Hakazaba** [comment]
I might be misunderstanding normalized landmarks vs landmarks (which i cant find a non normalized packet in the sdk)
My understanding is that normalized values always have a length of 1, which is ok if you just want a 2D camera position. But i want to use this to drive a rig and record motion capture files.

So ill need non normalized landmarks which have a z value to indicate depth, which i can then convert into unity's coordenate system.

**Comment by homuler** [comment]
`Landmark` and `NormalizedLandmark` are defined in [landmark.proto](https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/landmark.proto) and compiled into Landmark.cs.

> i cant find a non normalized packet in the sdk

`mediapipe::Packet<Landmark>` exists in C++ code, but I've not ported it yet because none of official solutions (e.g. Face Detection, Hands, etc...) returns it.

> My understanding is that normalized values always have a length of 1

If so, it does not make differences (then x^2 + y^2 + z^2 = 1), but in fact `NormalizedLandmark` does not represent a normalized vector, and the `x`, `y`, and `z` value are normalized individually (e.g. top-left is (0, 0) and bottom-right is (1, 1)).
cf. https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_landmarks_calculator.cc#L245

However, `Landmark` and `NormalizedLandmark` can represent either 2D or 3D position, and it depends on models and calculators you use. If `NormalizedLandmark` does not have `z` value, I guess the corresponding `Landmark` (if you can access it) also will not have it (some calculators may ignore z-value accidentally, but I don't know if it's true).

It's rather MediaPipe's question, and I think it'd be better to ask MediaPipe dev team which model or solution returns depth information and which not.

**Comment by Hakazaba** [comment]
Ah, just my misunderstanding then.

**Comment by kitmek1** [comment]
I wanted to know how can i use this plugin inside my project in unity

**Comment by doubld** [comment]
Hi! I managed to configure properly the dependencies required to the plugin, I built the .apk for Android and it works (: Since this was not very easy for me, I'm thinking of writing a tutorial on Medium in which I explain how I managed to configure the project and build the .apk. My question, so, is if I can do it, or there are any issues regarding licenses of MediaPipe or your plugin. For instance, can I cite your plugin in my tutorial? Sorry, but this is the first time I would do it so I don't know much about licenses, permissions etc.

**Comment by homuler** [comment]
@doubld Thank you!
> there are any issues regarding licenses of MediaPipe or your plugin. For instance, can I cite your plugin in my tutorial?

Yes, this plugin is distributed under MIT license, and you can use or cite it (in general, it would be better to mention or link LICENSE page, I don't mind if not).
If you'd like to distribute the binaries you built, please note that MediaPipe is distributed under Apache 2.0 license (probably you need to include LICENSE or make it visible to the users).
cf. https://github.com/homuler/MediaPipeUnityPlugin#license
