### ISSUE TITLE
Face Geometry Node

### ISSUE THREAD

**Issue by DontUnderstandCode** [homuler/MediaPipeUnityPlugin#593]
### Description

Hi, I'm just wondering if it's possible to use the face geometry calculator in a graph? I can see from the mediapipe project examples that it requires a particular .binarypb file that I'm not sure is available, (at least I couldn't find it). 
For context, I plan to input multi_face_landmarks into the calculator, and use the outputs to deform a face mesh of my own.

**Comment by homuler** [comment]
Yes, it's possible, but you need to do some additional work yourself (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/481#issuecomment-1067737300).

> use the outputs to deform a face mesh of my own.

If that's all you want to do, it may be better to build `Mesh` from landmarks directly since the `Mesh` `FaceGeometryPipelineCalculator` will return is not [UnityEngine.Mesh](https://docs.unity3d.com/ScriptReference/Mesh.html) (see https://github.com/keijiro/FaceLandmarkBarracuda/blob/0ff22f2ecbd2d73e8e04bb7dc3bd1649f5942ae7/Assets/Editor/TemplateBuilder.cs and https://github.com/keijiro/FaceMeshBarracuda).

**Comment by DontUnderstandCode** [comment]
Hi, Thanks for the fast reply, 
I'm not really sure how I'd go about building the .binarypb file mentioned, and in any case its hard to piece together the required syntax for setting up the nodes in the config file. 
However recreating the feature in c# seems doable, so I will try that 

Thanks again, and by the way this is a great project!
