### ISSUE TITLE
Library not loaded: @rpath/MediaPipeUnity.framework/MediaPipeUnity in Xcode

### ISSUE THREAD

**Issue by ZichunYuan** [homuler/MediaPipeUnityPlugin#602]
**Plugin Version or Commit ID**

v0.10.0

**Unity Version**

2021.3.4f1 (Silicon)

**Your Host OS**

MacBook Pro(16-inch, 2021) Monterey V12.2.1, M1 chip

**Target Platform**

iOS

**Description**

Successfully built to Unity.
Successfully built to Xcode.
Successfully built to iOS.
Unsuccessfully load Library @rpath/MediaPipeUnity.framework/MediaPipeUnity at runtime.

Looked into the below solution but still failed. Not sure what should be included in the AssetBundle.

"For those having the same problem: first make sure you got the .framework linked to your xcode and then make sure you have already installed the the assetbundle browser from the package manager and then built the main assetbundle. Make sure it's copied to StreamingAssets. After that my build was all good. Cheers."

_Originally posted by @samtremblo in https://github.com/homuler/MediaPipeUnityPlugin/issues/102#issuecomment-811430026_

**Code to Reproduce the issue**

When building to iOS on the Xcode after building from Unity to Xcode.

**Comment by homuler** [comment]
You should have opened the project using UnityEditor before building the iOS framework and some `*.meta` files had been removed.

If you cloned this repository, check out `Packages/com.github.homuler.mediapipe/Runtime/Plugins/iOS/MediaPipeUnity.framework.meta`.

Otherwise, check `Add to Embedded Binaries`.
![Screen Shot 2022-06-07 at 12 09 04](https://user-images.githubusercontent.com/4690128/172288085-dc5bbb0a-ecf6-41ed-9959-680eccd20546.png)

**Comment by homuler** [comment]
duplicates #385

**Comment by ZichunYuan** [comment]
Thank you so much for you help, homuler! Really appreciate it! Now it's working on iPad Pro(13inch 5th gen)!
