### ISSUE TITLE
What is the Timeout value actually for? What are good values etc?

### ISSUE THREAD

**Issue by ROBYER1** [homuler/MediaPipeUnityPlugin#672]
### Description

Just a quick question - I've been tasked with improving the performance of some windows PC builds using hand tracking, and I was wondering if the timeout value would make the hand tracking more responsive if the value was lowered from the default 50000 on the hands scene?

I can't see anything about Timeout in the docs or the wiki but I can assume that a lower value would make mediapipe run faster potentially?

From what I can see the main factors at play in performance are:
1-Webcam video refresh rate at different resolutions
2-Model complexity - Lite or Full
3-Max Num hands being set to 1 helps a lot for single hand apps
4-CPU strain on the device during runtime - CPU or GPU bound
5-Timeout value?

**Comment by homuler** [comment]
It does not affect the behavior of MediaPipe.
https://github.com/homuler/MediaPipeUnityPlugin/blob/436edb06f9b62c4af146903db9a21869c7ce2a89/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs#L80-L82

If your program does nothing when the output is empty, then this parameter may not be useful.
In the sample scene, `AnnotationController` will clear the current annotation when the output is empty, so it will mitigate flickering.
(If no new input is given, it is still meaningless since no new output will come)
