### ISSUE TITLE
 How can I draw the hand tracker ？

### ISSUE THREAD

**Issue by bbq82828** [homuler/MediaPipeUnityPlugin#723]
### Description

I can take out the hand landmarks now , How can I draw the hand tracker on one of the landmarks and the rest are not displayed?

**Comment by homuler** [comment]
Some contexts to understand your issue are missing, so please fill them using [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).

- Are you trying the sample scene or did you write your own code?
- What is "the hand tracker"?
- Screenshots to show your current situation
- etc...

**Comment by bbq82828** [comment]
Thanks in advance for your reply 
like the hand show in the image below I want to ask how can I draw only one of the points

<img width="359" alt="image" src="https://user-images.githubusercontent.com/56858145/186827494-7c095ff2-0fa9-4d1a-bf0a-95668764d4ca.png">

**Comment by homuler** [comment]
You can [get landmarks](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#get-landmarks), so you can also select one of the landmarks (cf. #619) and calculate its local position.
Then place some object (e.g. Sphere) at the calculated position, instead of calling `AnnotationController#Draw`, that will annotate all the landmarks.

**Comment by bbq82828** [comment]
Oh  I see. Thank you I'll try it
