### ISSUE TITLE
Start and Stop mediapipe processing

### ISSUE THREAD

**Issue by ehsanwwe** [homuler/MediaPipeUnityPlugin#747]
### Description

hello
i test
this command in the graph class
Stop(); ( it works good )
StartRun(ImageSource _imageSource) i use WebcamSource for image source , but didnt work for second round - first round called automaticaly

both of them just work for 1 time to stop and start the processing 
and i got blow error :
**Object reference not set to an instance of an object**
also i test 
graphRunner.OnHairMaskOutput ** -= ** OnHairMaskOutput;
it dosent change any thing

can any body show me a way to stop and start solution for multiple time ?

**Comment by homuler** [comment]
See https://github.com/homuler/MediaPipeUnityPlugin/issues/732#issuecomment-1236893275

**Comment by ehsanwwe** [comment]
this comment didn't help me
when because when i shutdown the bootstrap
the AR is alive and works
i want to turn of mediapipe in UI page and trun it on when the UI page will be hide

**Comment by homuler** [comment]
> when i shutdown the bootstrap

It seems to me that you're trying to reuse the sample scene, but it's not recommended.
If you still want to do that, note that the `Bootstrap` instance must be initialized once and only once.

> i want to turn of mediapipe in UI page and trun it on when the UI page will be hide

I think you don't need to stop the `CalculatorGraph` since it will stop soon after you stop sending the input.
If you want to initialize the `CalculatorGraph` again, then you can just do so (note that what the `Bootstrap` instance does must not be done more than once).
See also how the sample app pauses/resumes or stops the `CalculatorGraph`.
https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs#L38-L56

If you need more help, please use [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).
To be honest, the description is not clear to me and I don't understand your issue.

**Comment by ehsanwwe** [comment]
yes its works fine
