### ISSUE TITLE
How does it interacts with MediaPipe central repo?

### ISSUE THREAD

**Issue by Drunkensteinn** [homuler/MediaPipeUnityPlugin#748]
### Description

Greetings!!!!))) Would you be kind enough to explain how exactly it interacts with the central MediaPipe repo? And - can I write my own .cc/cpp calculators and after it, build a new .so/dll with new changes or modules? (Somewhere at Mediapipe core level) For example: I wish to write a few new calculators and a few new .pbtxt graphs, and call them in the Unity editor. How complicated it is? Or do I need to implement it from scratch? 

Kind regards!!!))))

**Comment by homuler** [comment]
This repository fetches the MediaPipe repository using Bazel.
https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/WORKSPACE#L55-L71

So if you have forked the MediaPipe repository and implemented some calculators, you can use the forked repository instead by specifying the URL.
If you've not forked it, I recommend you fork this repository and implement custom calculators somewhere under the `mediapipe_api` directory (because you need to maintain [patches](https://github.com/homuler/MediaPipeUnityPlugin/blob/f196f4631f81afb2f897116c5adbfead3768aab9/WORKSPACE#L61-L66) otherwise).
Of course, to implement them, you should be familiar with the MediaPipe C++ API.

See also #277.
