### ISSUE TITLE
Using Sample FaceMesh in Multiple Scene is not working

### ISSUE THREAD

**Issue by NeerajMehta** [homuler/MediaPipeUnityPlugin#782]
### Description

Hi, I am trying to Use Face Mesh Sample to work in multiple scenes where I am getting different facial expressions and landmarks with Light Estimation. All Scenes are working fine if run separately but when I am Loading scenes from one to another. Getting the following Error.

![Untitled](https://user-images.githubusercontent.com/7052504/200492491-1e4710c9-c211-4d0a-80ab-5af8ea98a438.png)

**Comment by homuler** [comment]
Will you describe what the problem is?
If you changed the code and the program stopped working, it is probably because of that change.

Actually, you can switch scenes if you start the app from [the Start Scene](https://github.com/homuler/MediaPipeUnityPlugin/blob/391d7d98b127ce41ceac85ec47f6126664f1bc4e/Assets/MediaPipeUnity/Samples/Scenes/Start%20Scene.unity).

**Comment by homuler** [comment]
@neersmehta Please read https://github.com/homuler/MediaPipeUnityPlugin/issues/747#issuecomment-1254906719 first.
If you need more help, please use [the support form](https://github.com/homuler/MediaPipeUnityPlugin/issues/new?assignees=&labels=type%3Asupport&template=support.yml).

**Comment by neersmehta** [comment]
@homuler So I am trying to Use an Alternative Camera i.e, NatDevice in FaceMesh Solution.
Here is the link for that https://docs.natml.ai/natdevice/prelims/getting-started
Can you suggest what changes I need to do I have done some changes as per your suggestions #738 and #343 but doesn't help.
