### ISSUE TITLE
Annotations right and left are flipped with webcam input 

### ISSUE THREAD

**Issue by dantonioangela** [homuler/MediaPipeUnityPlugin#876]
### Plugin Version or Commit ID

v0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

macOS Monterey Versione 12.3

### Target Platform

UnityEditor

### Description

The right and left landmark annotations are flipped when I only use a webcam as input. I put two pictures for reference where you can see that in the webcam the right and left (orange and blue) are reversed and in the one in the video they are not:

![wbcam](https://user-images.githubusercontent.com/48484241/225660086-f414a43b-9950-4461-a965-13d16bfea85b.png)

![video](https://user-images.githubusercontent.com/48484241/225660205-a3fa807a-4151-4429-b4ac-3d817fce21e5.png)

How can I solve this problem? because I want to animate an avatar and when I raise my right hand he will raise his left hand.

**Comment by fadiaburaid** [comment]
You should know which landmarks you are using to animate the avatar regardless the color. Mediapipe Unity Plugin just follows Mediapipe Pose Landmark Model referenced [here](https://google.github.io/mediapipe/solutions/pose#pose-landmark-model-blazepose-ghum-3d). I have personally used it and the 33 landmarks follow the model.  Check your webcam setting and make sure your camera input is not flipped (Should not be like a mirror) otherwise Mediapipe will mistake your right hand for left hand.

**Comment by dantonioangela** [comment]
I know which landmarks I'm using to animate the model, and in fact for the video input it works. But for webcam are simply flipped, and I would like to know what can I change in the files (maybe graphrunner.cs or webcamsource.cs) to adjust this thing because I cannot change the settings of my front webcam on Mac.

**Comment by homuler** [comment]
Check `Is Horizontally Flipped`.
![Screenshot_20230317_222118](https://user-images.githubusercontent.com/4690128/225917094-02f1a49f-7d67-477c-9442-5ffa311441f7.png)

**Comment by dantonioangela** [comment]
Thank you @homuler for your reply, I have just tried but it doesn't change anything :(

**Comment by homuler** [comment]
Wouldn't the color of the landmarks be swapped? (orange <-> blue)

**Comment by dantonioangela** [comment]
I don't think it is just the colour of the annotations, because I actually apply the landmarks to the avatar and for the videos everything is ok, only for the webcam the movements are reversed.

**Comment by homuler** [comment]
Do you take it into consideration that the input image can be flipped (so the output coordinates can also be flipped).

**Comment by dantonioangela** [comment]
Sorry but i'm not really sure, do you know where can I check this thing?

**Comment by homuler** [comment]
I don't know since it depends on your implementation. 
When you toggle `Is Horizontally Flipped`, if your right hand is annotated with blue color (it is correct, see https://google.github.io/mediapipe/solutions/pose.html#pose_world_landmarks), then your implementation should be wrong.

I'm not sure, but if you're already respecting [`ImageSource.isHorizontallyFlipped`](https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/ImageSource.cs#L66), then ignoring it may solve the issue, and if you're not, then respecting it would do.

https://github.com/homuler/MediaPipeUnityPlugin/blob/31de77b5ac782be5b06740cf4d6e8a6c100a5007/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/ImageCoordinate.cs#L487-L489
