### ISSUE TITLE
converting from model zoos

### ISSUE THREAD

**Issue by pjbaron** [homuler/MediaPipeUnityPlugin#93]
Hi Homuler, thanks for such a brilliant project, I've been having a blast playing with it and I'm delighted the mediapipe implementation of hand tracking is vastly superior to other projects I've tested using TFL alone.
I've been looking into using other pretrained models (e.g. from the ONNX model zoo), but I haven't been able to work out what the .bytes format this project uses for models actually is.  Could you let me know what type of model they are based on, and what processing is involved in getting them into .bytes format (even if it's just a rename)?
Cheers!

**Comment by homuler** [comment]
>  Could you let me know what type of model they are based on, and what processing is involved in getting them into .bytes format (even if it's just a rename)?

I just renamed `*.tflite` into `.bytes` so that they can be included in an AssetBundle file.
If MediaPipe can handle the format, extension is not much important.

https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/mediapipe_api/BUILD#L142
https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/mediapipe_api/import_model.bzl#L56

**Comment by pjbaron** [comment]
That's great thanks!
