### ISSUE TITLE
Question about how to improve inference performance :)

### ISSUE THREAD

**Issue by coke05288** [homuler/MediaPipeUnityPlugin#977]
### Description

i'm currently using this project you provided after building through docker in the window environment ;)

I've also run it on MacOS, and I found out that there is a difference in the frame of CameraView depending on the performance of the CPU when FaceDetection is performed through WebcamImageResource in asynchronous mode. Even if the CPU performance is low, I want to perform the same as the high-performance CPU, so I tried two ideas. 

The key is to reduce the resolution of the imageSource before making an inference.

The first implementation idea is to reduce the resolution of the imageSource in WebcamImageSource to make an inference. However, this method has not been resolved by reducing the texture size in the unity client stage because the process of passing the inference (building and transferring sidepacket) is based on the imageSource.

The second implementation idea was to run Webcam individually and improve performance by adding webcamtexture with reduced resolution to the availableImages[0] of StaticImageSource. However, it is not easy because the screen of camview is linked to ImageSourceSolution.

I'm writing down an issue because I'm wondering if there's a guide to improve performance other than the two ideas above :)

Thank you!

**Comment by homuler** [comment]
Is it OK to answer with the assumption that the program will be running on macOS?

First of all, since it's not possible to fundamentally improve the speed of inference itself (if you really want to do that, please ask to the MediaPipe developers instead), are you looking to improve the FPS? In that case, on the Unity side, I think you'll need to focus on improving input or output processing.

I'm not sure why it's failing, but I believe reducing the size of `ImageFrame` will make it somewhat faster. Additionally, I think there are other methods to build `ImageFrame` more efficiently and avoid blocking the main thread for a long time.

https://github.com/homuler/MediaPipeUnityPlugin/blob/c7771138cf2361f6184220424fa751ab90f60672/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs#L129-L159
